### ISSUE TITLE
ConEmu 下 scoop 安装异常

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#1]
我再conEMU下安装scoop时，出现以下问题：
运行 PS C:\Users\dell> iwr -useb get.scoop.sh | iex 这一步时，在未连接学校vpn情况下出现
![1b483d199b0164a55c6d93398f94943](https://user-images.githubusercontent.com/61767345/75839400-b6064b00-5e03-11ea-96de-ee84b36b0bad.jpg)
连接学校vpn之后出现
![09e4cfca6a67f8ee99b3e40cf9ef0a2](https://user-images.githubusercontent.com/61767345/75839460-d6360a00-5e03-11ea-8220-cc8fe4408990.jpg)
我是win10系统，麻烦老师啦！

**Comment by neolee** [comment]
这个是网络问题，换个网络或者换个时间再试，也可以试试网络代理。

学校的 VPN 不知道可不可以，我问下再答复你。

**Comment by unicorn-xia** [comment]
我换了时间，用了学校的vpn，安装成功了，谢谢老师！
