### ISSUE TITLE
jupyterlab 启动后目录为空

### ISSUE THREAD

**Issue by LauraWen** [neolee/wop-ecnu-pub#10]
![image](https://user-images.githubusercontent.com/46390542/76138097-1e149580-607f-11ea-8969-803e1ee99771.png)

老师好，在命令行运行jupyterlab后看不到文件，我尝试在命令行运行jupyter notebook也无法看到文件。（我原来使用的是anaconda下的notebook,不知道是工作路径还是环境的问题？）

![image](https://user-images.githubusercontent.com/46390542/76138186-5072c280-6080-11ea-9255-1bc4cbf478ba.png)

**Comment by neolee** [comment]
看上去是有错误发生。由于你的环境比较复杂，而且给出的截图没头没尾，仅凭这些信息很难判断。

首先按照 Wiki 中的指示，先执行下面的命令，提供你的基本信息：

```powershell
$PSVersionTable.PSVersion.Major
$env:Path

scoop update
scoop checkup

which python
python -V
pip -V
pip list
```

然后，给出你在命令行执行 `jupyter lab` 之后的完整截图，可能需要截好几屏，但都需要。

**Comment by LauraWen** [comment]
基本信息：（这里不知道为什么调用的是anaconda的python）

![image](https://user-images.githubusercontent.com/46390542/76139958-8ae45b80-6090-11ea-8294-48dccd4a7d64.png)

![image](https://user-images.githubusercontent.com/46390542/76139965-98014a80-6090-11ea-8c8c-1b1ecf3a27d4.png)

![image](https://user-images.githubusercontent.com/46390542/76140031-54f3a700-6091-11ea-91e0-67caa258bdf5.png)

![image](https://user-images.githubusercontent.com/46390542/76140036-5cb34b80-6091-11ea-8dcb-d5bda2c6b957.png)

jupyterlab 报错：

![image](https://user-images.githubusercontent.com/46390542/76140072-9dab6000-6091-11ea-9870-df644750d035.png)

![image](https://user-images.githubusercontent.com/46390542/76140080-aac84f00-6091-11ea-8039-c0b138f8076e.png)
 
之后就是重复的部分了

**Comment by neolee** [comment]
我猜测和你的新旧环境有冲突有关。建议你把 Anaconda 卸载掉再试试；或者也可以修改你系统的 PATH 变量，把 Anaconda 所在的目录都先去掉，然后再试试。

**Comment by LauraWen** [comment]
老师好，我昨天晚上尝试了删除path变量和卸载anaconda，都没有成功。
然后还尝试了
```
jupyter lab clean
jupyter lab build
```
也还是不能正常打开

**Comment by LauraWen** [comment]
老师好，问题已解决。 重新install jupyterlab和jupyterlab-server后正常打开。谢谢老师！
