### ISSUE TITLE
关于编程世界漫游指南的疑问

### ISSUE THREAD

**Issue by CHANCYstone** [neolee/wop-ecnu-pub#108]
老师，你好！
前不久我选的数据库课布置了一个大作业：是用python建立一个web服务，在网页上实现对数据库的增删改查
![image](https://user-images.githubusercontent.com/71212547/101762868-eb6d6100-3b18-11eb-914d-4494ddc72463.png)
想到老师之前的关于web的视频，进行了学习。
可是正如老师所说的，web的范围很大，以至于自己甚至一直都在“漫游”
一方面，自己不想单纯地以完任务地心态把大作业给copy式地做完，想通过老师所说的先进行任务分解，在解决问题中学习。
可是另一方面，感觉自己搜索到的东西，缺乏被自己实践的过程，在具体的例子之间，和webpy这些教程之间反反复复，花了很多的时间，却收获的不多。
感觉缺乏引领之后，总是在漫游。
想就如何系统性的继续学习，和如何训练自己解决问题能力向老师咨询相关建议。

**Comment by neolee** [comment]
这个作业实质上包含两个部分：

1. 设计一个描述家政人员信息的关系模型；
2. 在数据库中实现这个关系模型（一个或者多个表）；
3. 用 Python 实现一个对上述表进行 CRUD 操作的 web 页面。

这里面前两步应该不难，最后一步，你们课程有教么？没有的话，从零开始学会这个要费点劲，建议先把我之前的实践案例3过一遍，然后上网搜 webpy data CRUD 之类的关键词，找个 tutorial 出来学习。

**Comment by CHANCYstone** [comment]
嗯嗯，老师一番折腾，我们小组弄完了，最后是队友用djiango把后端给解决了（同样是没学过，靠着在网上找，他把给做出来了），总算是松口气
您说让找网上的tutorial进行学，我就在网上找，https://webpy.org/docs/0.3/tutorial 是像这样子的tutorial么？
我感觉这个学起来好生硬啊，尤其是到mysql和webpy的链接一环，虽然英文tutorial上的单词都认识，可是做起来十分的吃力
我还找到了一个https://github.com/webpy/webpy-examples GitHub上的例子，但是可能是因为缺乏html相关知识的缘故，这个github上的内容实在是丰富，太难啃了，
可能是因为deadline 的缘故自己一直没能有个好心态，放不轻松，没有放开，最后也没学会
不知道老师关于自学方面有没有一些建议

**Comment by neolee** [comment]
有些工具的官方教程写的比较好，有的则不太好，webpy 那个 tutorial 写的就不太好，至少对新人很不友好。但仔细搜索，只要是比较流行的工具，一般会有不错的第三方 demo 或者 tutorial 可用。

你们做这个比较困难的根源在于你们对 Web 的基本知识不熟悉，这部分包含两步：
1. 用 HTML+CSS+JS 绘制用户界面；
2. 根据用户操作调用后端的 Python 来增删改查数据库的数据。

我之前录制的实践案例视频中第三个 https://www.bilibili.com/video/BV1B7411d7dY/ 对这两方面都有涉及，可以作为一个入门视频来看——如果能把那里面的内容都吃透，应该会挺有帮助的。

**Comment by CHANCYstone** [comment]
好的谢谢老师，打算寒假回去自习学一学这方面知识

**Comment by CHANCYstone** [comment]
对了老师，关于接下来学习有没有一些书籍的推荐呀？
在网站上看到老师自己装的电脑（也太酷了吧）还会写web，还会写程序，，，
感觉这三者，还是是挺分离的
有没有书能够帮助我们这样的小白了解计算机世界的全貌的呀！

**Comment by neolee** [comment]
“计算机世界的全貌”很复杂，如果你保持好奇和好学的心，不断提升自己获取知识和学习的能力，到我的岁数肯定会的比我多 😄

课程最后一讲“编程世界漫游指南”介绍了编程世界的一个主体部分，可以参考里面的分类找自己感兴趣的一点点学着试试。
