### ISSUE TITLE
在 ConEmu 中用 code 无法运行 VScode

### ISSUE THREAD

**Issue by jingluo-star** [neolee/wop-ecnu-pub#11]
老师好，我是win10系统，已安装VScode
![1 2](https://user-images.githubusercontent.com/61736909/76140974-d3087b80-609a-11ea-9261-c5124b9aaae4.PNG)
但是我在ConEmu中运行```code .```代码后出现了
![1 1](https://user-images.githubusercontent.com/61736909/76141019-6c379200-609b-11ea-8b99-224d9b53deb2.PNG)
这是怎么回事呢

**Comment by neolee** [comment]
已有类似问题，看看 #8 对你有无帮助。

**Comment by jingluo-star** [comment]
谢谢老师，重启就解决了！
