### ISSUE TITLE
当没有任何变量指向一个对象时对象去了哪里？

### ISSUE THREAD

**Issue by dishangti** [neolee/wop-ecnu-pub#110]
如果我们删除了一棵子树，而且将所有原来可能保存着这棵子树的变量都赋值为None，那么以后似乎再也无法再次使用这棵子树了？这棵子树哪去了呢？

**Comment by neolee** [comment]
Python 解释器会管理内存里的对象，没有任何变量指向的对象，会被解释器清理掉以回收可用内存——这个技术叫做“自动垃圾回收（*garbage collection*）”。
