### ISSUE TITLE
大作业里 add_children() 和 find() 是要完成什么操作

### ISSUE THREAD

**Issue by wmy256** [neolee/wop-ecnu-pub#112]

**Comment by neolee** [comment]
为啥课上不问呢？为啥假期前不问呢？问的时候为啥不至少先自己做些推测呢？

- `add_children(self, node, children)`：把列表 `children` 中的所有元素都加为 `node` 的子节点。
- `find(self, name)`：在 `self` 为根节点的树中查找名字叫 `name` 的节点（或者如果你愿意的话，查找名字里包含 `name`的也行）并返回该节点。
