### ISSUE TITLE
安装 jupyterlab/toc 错误 “No 'jupyterlab' key”

### ISSUE THREAD

**Issue by Fanfan1031** [neolee/wop-ecnu-pub#114]
![image](https://user-images.githubusercontent.com/48583829/108944863-8f859380-7696-11eb-8d1b-11818b72f340.png)

**Comment by Fanfan1031** [comment]
老师，jupyter lab的版本是1.2.1；nodejs版本是13.0.1；安装提示"@jupyterlab/toc" is not a valid extension: No 'jupyterlab' key

**Comment by Fanfan1031** [comment]
![image](https://user-images.githubusercontent.com/48583829/108957430-6a038480-76ac-11eb-855f-faf60628318f.png)

**Comment by neolee** [comment]
好像这个包是出了一些问题（服务器那边的，和你没有关系），等一阵子看看它会不会修复吧。目前不装也不影响学习。
