### ISSUE TITLE
有时候编程让自己感到莫名的压力

### ISSUE THREAD

**Issue by CHANCYstone** [neolee/wop-ecnu-pub#115]
老师你好！
        近来在编程的过程中受挫，来GitHub向老师请教。
学完老师的python课后，本来对编程这件事情自信满满。可后来，web实现的梗塞；以及最近，在学习R语言时，老师让我们下载rstudio，我就想到或许jupyter 应该能达到同样的效果，在网上搜索jupyter 和 r 的相关https://www.datacamp.com/community/blog/jupyter-notebook-r 比如这篇，以及其他一些文章，但是在尝试的过程中，发现很多基本的知识例如console是什么都不太懂，scoop中下载了r 和 rstudio 只会启动 rstudio 却不会启动r。

虽说，遇到问题有Google，可以一点点查，试，但是前几天的举步维艰，让我感到莫名的压力。

看老师的web实例里教的学习新知识的方法，受益匪浅：定义问题，理解问题，提出方案，学习tutorial。

但是知易行难，解决未知问题时，并不敢打包票自己试就能做出答案，有些anxious。

多谢老师百忙中抽出时间答复

**Comment by neolee** [comment]
简单谈几点感想：
1. 千万不要贪，《进入编程世界》只是开始，这门课毕业之后选定一个领域深入学下去，不要同时搞太多头；
2. 如果你仔细体会和，就会发现我的课程中经常穿插一些工具和通用思维的讲解，这是学习编程的一个规律，就是学一个具体领域和工具的时候可以顺便学一些通用思想和工具，磨刀不误砍柴工；
3. 学编程就是要时间和经历的，要学的东西太多了，所以需要找到一个自己感兴趣的领域持续钻下去，这个过程中会有很多附加收获，前提是你善于学习而且别太功利。

**Comment by CHANCYstone** [comment]
谢谢老师的答复，谢谢！

**Comment by neolee** [comment]
顺便说下你提到的几个主题。Web 开发内容很多很杂，需要学很久，不着急，我之前有发过一个不长的视频介绍 Web 开发学习的起步建议，可以参考：https://www.bilibili.com/video/BV1hv411y7Mj/ 

还有之前的三个编程实践案例中的两个都和 Web 开发的入门有关，也推荐反复学习练习到搞懂：
https://www.bilibili.com/video/BV1hE411M7Rt/
https://www.bilibili.com/video/BV1B7411d7dY/

至于 R，我也不专业，不过初学时就用 RStudio 就可以了，进去之后有个窗格就是 R 的 REPL（还记得这是什么意思么？），可以直接在里面写代码运行测试了，它会自动使用你安装好的 R 环境。

**Comment by neolee** [comment]
> REPL我忘记了。。。 我现在了解到rstudio有四个窗口一个是编辑区，一个是console视窗，还有一个是文档区，还有一个是环境，REPL应该就是编译吧。https://yijutseng.github.io/DataScienceRBook/video.html#video 目前在参考这个进行学习。

REPL 在我课程的第一讲里有，就算不记得，搜索一下也很容易得到。

> 1. 编程需要做笔记嘛？感觉如果做笔记就应该以掌握思想为目的来做笔记。可是编程的思想这样的事情，感觉用笔记难以记下来呀（就是学的思想学的很浅）。似乎笔记对编程这门东西效果并不是很突出。

笔记不是必须的，不过你如果觉得“用笔记难以记下来”，就反而要多写写了，写不出来的原因通常都是没想明白，多写几次，写完自己读一遍，再改，如此反复，对提炼思维有帮助。

> 2. 如何锻炼提升自己的编程能力？我个人一个初学者，对学编程的一个比较深的感触是：“解决题目，或者项目的能力较弱”，如果没有先例，自主一下子就解决问题较为困难。也有在想，应该是做的训练不够的原因，可能需要做些LeetCode的题目？（这是我在网上看的。。）

刷题可以帮助提升：1. 增长见识；2. 把现实问题抽象为算法的能力；3. 熟悉更多常用算法。你可以试试。

**Comment by CHANCYstone** [comment]
嗯嗯，谢谢老师。
