### ISSUE TITLE
anaconda 是否需要下载

### ISSUE THREAD

**Issue by CHANCYstone** [neolee/wop-ecnu-pub#116]
老师你好！

在cvxpy安装失败后
![image](https://user-images.githubusercontent.com/71212547/111408194-e0c1f980-870f-11eb-916f-65d9bf5c8c13.png)

从官网中了解到用anaconda安装会更好些（上面用官网另一个推荐虚拟环境安装的结果），于是我了解了一下anaconda的资料，发现它似乎和pip有点像，而且本身有虚拟环境的效果，常用于数据科学，然而用scoop安装后发现 anaconda竟然和jupyter有交集导致原来的jupyter无法使用。

似乎要jupyter卸载后，再下载anaconda会好一些？但是在这样做之前想要向老师进行咨询

**Comment by neolee** [comment]
一般来说不要同时使用 pip 和 anaconda，会有很多问题。

目前我比较推荐的是 pip，如果 pip 安装第三方包遇到问题可以使用国内的镜像站点，比如清华的这个：

https://mirrors.tuna.tsinghua.edu.cn/help/pypi/

**Comment by CHANCYstone** [comment]
多谢老师！
