### ISSUE TITLE
请教老师如何学网络协议栈

### ISSUE THREAD

**Issue by CHANCYstone** [neolee/wop-ecnu-pub#117]
老师，你好！

最近希望了解更多网络协议栈的东西，于是找到了《网络是怎样连接的》一书，书本很吸引人：计算机网络概论 “趣味图解版”，“生动有趣”。然而，看了几十页，却发现次数似乎还蛮硬核的，觉得网络相关的东西还是很细致的，有很多的规矩。
希望请教老师，关于网络协议栈有没有什么比较推荐的书籍呀。

谢谢老师！

**Comment by neolee** [comment]
网络编程本来就有一定门槛，如果涉及网络协议的设计和实现，就更硬核了，不建议在早期去啃，入门初期多研究应用领域的问题比较好。

如果准备好了，可以去啃啃经典《TCP/IP Illustrated（TCP/IP详解）》（先第一卷，然后第二卷），也可以看稍微浅显一点的《Computer Networking - A Top-down Approach（计算机网络：自顶向下方法）》；学习过程中要多动手，可以从抓包开始，达特茅斯大学有个实践案例可以照着做： https://www.cs.dartmouth.edu/~campbell/cs60/assignments.html

**Comment by CHANCYstone** [comment]
查了下老师推荐的书和网站后（咽口水），
果然十分hardcore，
多谢老师！
