### ISSUE TITLE
numpy 中的 bool 型矩阵

### ISSUE THREAD

**Issue by CHANCYstone** [neolee/wop-ecnu-pub#119]
```
# question
sum_1 = 0
x = np.array([True,True])
for i in x:
    sum_1+=i
sum_1


index_sum = x[0]+x[1]
index_sum

sum_2 = 0
test = np.array([True,False])
for i in test:
    sum_2+=i
sum_2

index_sum_2 = test[0]+test[1]
index_sum_2
 ```

老师你好！
了解到True = 1 False =0 后，我昨天用 True和 False 的 求和值进行了一个简单的判断

然而却发现：
用for 循环得到的求和值 sum 是一个 Integel 正常的 1 和 0 的求和
然而 用其index 来求和时
却返回 一个布尔型值 且发现这个求和过程：只要任意有一个加数为 True 则其求和即为True
而不是我预期的整数的求和。。。

我在想是不是numpy所特有的于是我对list进行了同样的操作
```
ls = [True,True]
sum = 0
for i in ls:
    sum+=i
sum
indexsum = ls[0]+ls[1]
indexsum
 ```
发现 python 中的布尔型列表 在用index 求和时与预期相符 
而与numpy 不同，不知道是为什么。。
是因为取index时 和迭代器取 数不一样么？可为什么python list中没有这样的效果？

**Comment by neolee** [comment]
**简单的答案**：numpy 里的数据类型和 Python 原生类型不一样，数据之间可以做的操作也有差别，虽然看上去似乎一样。

**复杂的答案**：

Python 的基础数据类型来源于 C 语言的数据类型，为了实现 Python 语言特性而进行了封装，比如 C 语言没有 bool 类型，就直接用 1 和 0 表示，Python 封装后变成了 True 和 False，实际上已经很不一样了。

numpy 是进行数学运算用的基础库，为了满足运算所需要的高性能，numpy 对所有基础数据类型都做了自己的处理，基本都用 C 语言重新实现了其各种运算和处理功能，在此过程中不得不进行了一下魔改，比如 1 和 0 直接可与 True 和 False 互换。

你遇到的问题本质上是因为在 numpy 的数据类型里，`+` 这个操作符既可用于数值类型也可用于布尔类型，同时 `0` 和 `1` 既可以表示数字也可以表示布尔型的值。

在第一种情况下，你的逻辑是这样的：
* `sum = 0`
* `sum = sum + x[0]`
* `sum = sum + x[1]`
注意，这里你已经一开始就指定了 `sum` 的值为 1，这样它的类型就确定为整数了，后续的运算就强制在整数域进行，`x[i]` 都被理解为整数来处理了

而第二种情况下，你直接计算：
* sum = x[0] + x[1]
这时候 `x[0]` `x[1]` 都是布尔型值，这时候 `+` 被定义为逻辑或运算，等同于操作符 `or`，结果就是个 bool 了。

而在 Python 原生的类型里，两个 bool 型值并不能直接用 `+` 相加，这个 `+` 只能用于数值类型，于是 Python 就把列表里的两个元素都自动转化为整数，结果就是整数了。

**Comment by CHANCYstone** [comment]
喔喔！！谢谢老师
