### ISSUE TITLE
使用 Scoop 下载 python 时找不到 pythonw

### ISSUE THREAD

**Issue by hashiqi-ly** [neolee/wop-ecnu-pub#12]
老师，我按照教程下载conemu后使用scoop下载python但是提示找不到pythonw.ex
<img width="460" alt="1" src="https://user-images.githubusercontent.com/61896361/76142708-09e68d80-60ab-11ea-957c-21396c525eb2.png">

之后启用scoop的checkup发现两个问题
<img width="458" alt="2" src="https://user-images.githubusercontent.com/61896361/76142724-3ac6c280-60ab-11ea-894b-d95990a5807f.png">
但是继续向下排查时，却有两个网站进不去，没办法完成下载
<img width="460" alt="3" src="https://user-images.githubusercontent.com/61896361/76142751-6c3f8e00-60ab-11ea-811f-5a07b9b0081e.png">
<img width="457" alt="4" src="https://user-images.githubusercontent.com/61896361/76142776-af99fc80-60ab-11ea-96a1-a55abbf31dcc.png">
之后我在网页上打开这两个网站也打不开。
请问老师我是哪里出了问题？

**Comment by neolee** [comment]
首先你需要装好 dark 和 innounp 这两个包。然后你装的时候感觉是网络有点问题，可以换个时间或者换个网络试试，或者尝试网络代理。

**Comment by hashiqi-ly** [comment]
老师，我现在下载了这两个包了，但是还是找不到pythonw，并且checkup以后显示没有问题
<img width="464" alt="987b9ecb04774c22364a8ab54de9c5e" src="https://user-images.githubusercontent.com/61896361/76144599-03f9a800-60bd-11ea-9490-4e95f67d6a21.png">

**Comment by neolee** [comment]
试试下面的命令：

```powershell
scoop uninstall python37
scoop install python37@3.7.4
```

**Comment by hashiqi-ly** [comment]
老师我已经重启了，但是还是不行
<img width="371" alt="ce08b0b8a7f0197e3449b5c89a4df86" src="https://user-images.githubusercontent.com/61896361/76146292-732ac880-60cc-11ea-97e9-6a526211229e.png">
之后我换用python3.7.6，也是同样的结果，checkup之后还是没问题
<img width="458" alt="a02afbdf7ca47a88474232df16884f5" src="https://user-images.githubusercontent.com/61896361/76146308-8c337980-60cc-11ea-9b2c-5602d33a38ec.png">
我是不是需要把原来下载的python卸掉

**Comment by neolee** [comment]
你原来下载的 Python 是指？

另外让你试 `scoop install python37@3.7.4` 为啥你每次都安装输入的都是 `3.7.6` 呢……

**Comment by hashiqi-ly** [comment]
因为安3.7.4出现了这个
<img width="371" alt="ce08b0b8a7f0197e3449b5c89a4df86" src="https://user-images.githubusercontent.com/61896361/76154846-41dae880-611e-11ea-8c6f-b055ff673e39.png">
让我想起来电脑里原来有3.7.6

**Comment by hashiqi-ly** [comment]
因为之前安3.7.4会出现
<img width="371" alt="ce08b0b8a7f0197e3449b5c89a4df86" src="https://user-images.githubusercontent.com/61896361/76156081-0cd79180-6130-11ea-86ae-65bb476e2ae2.png">
然后我就想试试3.7.6
后来发现不可以，我就把我原来电脑里的python全都卸载了，现在安装成功了
谢谢老师
