### ISSUE TITLE
KFCoding 无法登录

### ISSUE THREAD

**Issue by yooquu** [neolee/wop-ecnu-pub#13]
![H}O~%Q1WT18$_UX7DA1Y27T](https://user-images.githubusercontent.com/61874605/76143648-23d89e00-60b4-11ea-8314-ffb6ac3e9b30.png)
老师好！我想知道使用Kfcoding平台是否有必要，因为我无法使用自己学号登录进入该平台。

**Comment by will-ww** [comment]
还是需要的，请王皓月助教帮忙看一下~

@neolee 另外，我@的时候，好像好不能@助教，只有neolee和WuShaoling能够自动@出来。

**Comment by sunshinemingo** [comment]
现在应该可以登录了

**Comment by yooquu** [comment]
可以了，谢谢老师

**Comment by neolee** [comment]
> @neolee 另外，我@的时候，好像好不能@助教，只有neolee和WuShaoling能够自动@出来。

好像是只能 @ contributor 和上下文出现过的人。
