### ISSUE TITLE
在 ConEmu 中只输入 cd 不前往用户 Home 目录

### ISSUE THREAD

**Issue by jingluo-star** [neolee/wop-ecnu-pub#14]
已配置好所有环境，并且支线任务其他操作都可以，但是发现在win10环境下这个操作不行
![捕获1](https://user-images.githubusercontent.com/61736909/76154000-d4c05680-610f-11ea-8e67-d5893e2a878e.PNG)

**Comment by neolee** [comment]
如果执行 `cd ~` 呢？

**Comment by jingluo-star** [comment]
可行！
![1 3](https://user-images.githubusercontent.com/61736909/76156301-7a38f180-6133-11ea-8584-18c526d60a07.PNG)

**Comment by neolee** [comment]
`~` 是用户 home 目录的 shortcut。

如果要进一步偷懒，只用 `cd` 就完成，需要安装 busybox。

**Comment by jingluo-star** [comment]
哦哦，这样啊
我已经安装了 busybox , 似乎不是里面的功能
![捕获4](https://user-images.githubusercontent.com/61736909/76156769-e61e5880-6139-11ea-8741-6e197dc9d0bb.PNG)

**Comment by neolee** [comment]
我查了下，好像不用 busybox 也应该是可以的。`cd` 实际上是 PowerShell 的命令 `Set-Location` 的别名，而 `Set-Location` 的文档里明确说了，没有参数时缺省是进入用户 home 目录：

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-location

你的 PowerShell 版本是？

**Comment by jingluo-star** [comment]
![捕获1](https://user-images.githubusercontent.com/61736909/76157057-cc334480-613e-11ea-8448-dfdde415d820.PNG)

**Comment by neolee** [comment]
这个有点奇怪呢，还没找到有价值的信息，先搁着吧……
