### ISSUE TITLE
使用 git commit 的简洁代码时发现无法提交移动操作

### ISSUE THREAD

**Issue by jingluo-star** [neolee/wop-ecnu-pub#15]
使用 git commit 的简洁代码,即``` git commit -a -m "information" ```时发现无法提交移动操作
![捕获2](https://user-images.githubusercontent.com/61736909/76154718-1b1bb280-611c-11ea-96fc-3748453d9e30.PNG)
经尝试，似乎只能通过add操作和commit操作后才能提交到版本仓库，是否是如此呢？

**Comment by neolee** [comment]
记住，commit 只是将 staging area 里的内容提交到版本库；而你 rename 的动作对 git 来说是少了一个旧文件又多了一个新文件，必须用 `git add` 命令把新文件加入到 staging area 之后 git 才能开始处理它。

**Comment by jingluo-star** [comment]
但这个代码里不是有``` -a ``` 嘛，课上不是解释说这个代码可以加入 staging area 直接到版本仓库，为什么这个新文件就不行了呢。

**Comment by neolee** [comment]
`-a` 只是代表自动包括**已在版本库中的**文件的所有修改，不包括新加入的文件。git 对“把新文件加入版本库”这件事情比较谨慎，要求手工操作。

**Comment by jingluo-star** [comment]
哦哦，我懂了，因为课程里的文件 README.md 是已经加过的旧文件，所以可以用这个代码，这个是新的不可以. 要注意新旧！
好，谢谢老师！
