### ISSUE TITLE
KFCoding 无法登录

### ISSUE THREAD

**Issue by ccccchao** [neolee/wop-ecnu-pub#16]
尝试用学号登录，显示“用户不存在或密码错误”……

**Comment by will-ww** [comment]
你的学号是？

**Comment by will-ww** [comment]
需要同时选择所在的学校～

**Comment by ccccchao** [comment]
所在的学校我选了呀…
我的学号是10185101185~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Will Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月8日(星期天) 上午10:02
收件人:&nbsp;"neolee/wop-ecnu-pub"<wop-ecnu-pub@noreply.github.com&gt;;
抄送:&nbsp;"ははは"<1404614828@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/wop-ecnu-pub] KFCoding无法登陆 (#16)




需要同时选择所在的学校～

**Comment by sunshinemingo** [comment]
现在应该可以使用你的学号登录了

**Comment by ccccchao** [comment]
可以了！谢谢(๑′ᴗ‵๑)~
