### ISSUE TITLE
scoop 自检后不能运行解决命令

### ISSUE THREAD

**Issue by Alex-li-zr** [neolee/wop-ecnu-pub#17]
在使用scoop checkup后，按系统推荐输入命令，但显示不允许所请求的注册表访问权。

![批注 2020-03-08 101420](https://user-images.githubusercontent.com/61897461/76155333-bb2a0980-6125-11ea-9910-d7efd95d71c6.jpg)

**Comment by jingluo-star** [comment]
感觉是要以管理员身份运行 ConEmu

**Comment by Alex-li-zr** [comment]
我试了一下，好像这个conemu没有运行这个命令
![po ](https://user-images.githubusercontent.com/61897461/76156234-5032ff80-6132-11ea-8c32-88c81d2d954e.jpg)

**Comment by neolee** [comment]
最后一个截图已经成功了吧，你可以试试用下面的命令检查（稍微想想就能猜出这两个命令分别干啥的吧）：

```powershell
Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled'
```

**Comment by Alex-li-zr** [comment]
解决问题了，谢谢啦！
