### ISSUE TITLE
下载 python 失败

### ISSUE THREAD

**Issue by chenlonghao** [neolee/wop-ecnu-pub#18]
PS C:\Users\86139> scoop install python
ERROR It looks like a previous installation of python failed.
Run 'scoop uninstall python' before retrying the install.
WARN  'python' () is already installed.
Use 'scoop update python' to install a new version.
出现上述这一串代码

**Comment by neolee** [comment]
提示很清晰呀，之前遗留未成功的安装残余，先 scoop uninstall 之，然后再重新安装。

另外，请严格按照指南一步步操作，你这安装命令是不对的，会安装 3.8 的 Python。

**Comment by chenlonghao** [comment]
> 提示很清晰呀，之前遗留未成功的安装残留，先瓢卸载之，然后再重新安装。
> 
> 另外，请严格按照指南一步步操作，你这安装命令是不对的，会安装3.8的Python。

**Comment by chenlonghao** [comment]
& : 无法将“C:\Users\86139\scoop\shims\..\apps\scoop\current\bin\scoop.ps1”
项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包
括路径，请确保路径正确，然后再试一次。
所在位置 C:\Users\86139\scoop\shims\scoop.ps1:3 字符: 71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args
...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\86139\...t\bin\scoo
   p.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException 
出现这一串是怎么回事。。。

**Comment by neolee** [comment]
Scoop 没装成，可能是网络原因，安装中断之类的问题。需要重新安装 Scoop，可以看 Wiki，里面有方法。
