### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by daixiaolong520** [neolee/wop-ecnu-pub#19]
无法将 iwr项 识别为cmdlet 函数 脚本文件或可运行程序的名称，请检查名称的拼写

**Comment by neolee** [comment]
你的系统不支持 `iwr` 这个命令，原因是 PowerShell 版本过低，按照配置指南要求，PS 版本要求 5 或者更高。需要升级你的系统或者安装必要的组件。配置指南中都有写。

顺便说下，你这个问题可以作为反面典型了：

1. 标题就一个“问题”，内容也没头没尾，没说你干了啥，希望得到啥，实际得到啥，如果问题本身都懒到这种程度了，别人为啥要费劲回答呢？不过我说过大家都有新人光环，所以我这里还是认真回答了；
2. 没有按照配置指南一步步操作，否则根本到不了这一步，因为你的系统版本（确切地说 PowerShell 的版本）过低，配置指南第一步就过不了。
