### ISSUE TITLE
ConEmu 下安装 git 的相关问题

### ISSUE THREAD

**Issue by Fioooona** [neolee/wop-ecnu-pub#2]
老师好，我是win10的系统，已经按步骤行至安装git的部分，已经安装了7zip，innounp，dark，但在装载git时频繁出现这样的情况，请问怎么解决这个问题呢？
![捕获](https://user-images.githubusercontent.com/61745742/75839625-3927a100-5e04-11ea-8bce-21f85066feab.JPG)
谢谢老师！

**Comment by neolee** [comment]
这个是网络问题，换个网络或者换个时间再试，或者试试网络代理。

**Comment by Fioooona** [comment]
嗯嗯 百度已更换渠道解决。谢谢老师！
