### ISSUE TITLE
下载 scoop 过程出错

### ISSUE THREAD

**Issue by ecnu10195000414** [neolee/wop-ecnu-pub#20]
![微信图片_20200308231709](https://user-images.githubusercontent.com/61929330/76176600-62717400-61ec-11ea-8e64-73df5cf178c4.png)
![微信图片_20200309094131](https://user-images.githubusercontent.com/61929330/76176612-669d9180-61ec-11ea-9a1a-d9cda398a9cc.png)
第一、二次下载scoop的时候分别出现图一图二的代码，麻烦老师帮忙看一下，谢谢。

**Comment by xiaoya-Esther** [comment]
应该是第一次下载时出现网络问题连接中断，你试着把C:\Users\Administrator\ 目录中的scoop文件夹删掉再重新下载一次

**Comment by ecnu10195000414** [comment]
谢谢！按照这个方法我已经成功下载了。
