### ISSUE TITLE
Git 推送本地 Repository 出现问题

### ISSUE THREAD

**Issue by ECNUACRush** [neolee/wop-ecnu-pub#22]
老师。我想把我本地的一个小程序推送到github上面来，但是新建仓库的时候我想试试template。如下：
![image](https://user-images.githubusercontent.com/49430264/76404049-cc427700-63c0-11ea-83ab-f2dc09b6d5ea.png)
创建好之后发现仓库里面已经有很多初始文件了，尝试之前的推送命令：
`git remote add origin https://github.com/ECNUACRush/ECNU_peach_reading_vBeta.git`
`git push -u origin master`
推了一下一堆报错，大致看了一下好像是有冲突。
![image](https://user-images.githubusercontent.com/49430264/76404332-4246de00-63c1-11ea-86d9-668620997c6f.png)
用`git pull`试着拉一下也没有效果。
![image](https://user-images.githubusercontent.com/49430264/76404425-69051480-63c1-11ea-8e04-5cab2af1db46.png)
百度搜了一下让我1.先删除远程 Git 仓库 2.再添加远程 Git 仓库。操作了一下发现还是没用。
然后我直接进github手工delete了那个repository，又重新新建了一个不用template的repo，同时把我本地的小程序换了个路径以及加了个readme（害怕这里有冲突），重新推送的时候发现又有新的报错：不太明白哪里出了冲突。
![image](https://user-images.githubusercontent.com/49430264/76404716-e3ce2f80-63c1-11ea-9bcc-2a9f84db3205.png)

**Comment by neolee** [comment]
你要把本地的推上去的话就不能选 Template，因为你选了的话，远端仓库（repo）里就有东西，这样你本地有东西，远端有别的东西，就没法 push 了。

所以你一定要事先选好是再本地还是远端做初始化，如果是本地初始化，那么 GitHub 上就要是一个绝对空的；反之，如果在远端做初始化，本地就不要做事，把远端建好，clone 下来，然后再在本地做事。

**Comment by ECNUACRush** [comment]
好的。我以后注意。但是我现在创新的仓库再推本地那个小程序，它也不给我推了。报错是这样的，有什么解决方法吗？
![image](https://user-images.githubusercontent.com/49430264/76411659-33febf00-63cd-11ea-8df7-e95f30dcc225.png)

**Comment by neolee** [comment]
先删掉你之前加的 remote origin，参考这个官方帮助：

https://help.github.com/en/github/using-git/removing-a-remote

然后再重新来过就可以了。

**Comment by ECNUACRush** [comment]
Cover that！谢谢老师。
