### ISSUE TITLE
运行VSCode时出错，无法打开Code 这个目录

### ISSUE THREAD

**Issue by xiaolv333** [neolee/wop-ecnu-pub#24]
![image](https://user-images.githubusercontent.com/61935828/76718321-5b5cdf80-6771-11ea-9fc4-f0fef678f179.png)
前面的环境配置问题都已经解决，但在试运行VSCode时出错

**Comment by neolee** [comment]
如果正确安装了 Visual Studio Code 的最新稳定（Stable）版本，那么重启一下应该就可以了。
