### ISSUE TITLE
Win10 的“应用与功能”是否就属于包管理器呢？注册表又扮演了什么角色呢？

### ISSUE THREAD

**Issue by jiangsc17** [neolee/wop-ecnu-pub#27]
我注意到了两件事：
1.有些软件有可执行文件和压缩包两种
2.有些软件卸载后在注册表中还有残留
所以我很好奇在软件管理中，注册表又扮演了什么角色呢？

**Comment by neolee** [comment]
1. Windows 10 的“应用与功能”可以看做是一种软件包管理的能力，但是太弱了，就像你说的，它没办法完整删除一个软件，没法方便的更新软件，里面的软件也缺乏统一性，完全看用户自己，有些软件安装完毕甚至都不会把自己注册到里面去，卸载入口都找不到，等等。

另外我们学习编程，经常会用到一些命令行的软件，这些软件的安装和管理完全可以做的非常简单有效，用 Windows 的那一套就不合适了。所以有人学习 *nix 上的做法，通过包管理工具和一个汇集大量软件包标准管理信息的网络服务来实现方便而强大的软件包管理，Windows 下最成功的是两个：Chocolate 和 Scoop，我自己试下来觉得 Scoop 更易用一些，多以推荐大家使用这个。

2. 注册表相当于 Windows 自己以及所有软件都可以使用的一个“配置信息数据库”。注册表自己是一个类似文件系统的树形结构，有一个唯一的根节点，然后分了几个大区，符合规矩的软件都能在里面写自己独有的配置信息，Windows 集中管理这个数据库。不过由于历史原因和管理上的困难，里面的数据很容易成为垃圾——毕竟懂规矩而且守规矩的软件并不多。

p.s. Unix-like 系统中没有注册表这样的机制，因为 Unix-like 的系统中，文件系统就是唯一的，有一个固定的根路径（`/`），所以直接把配置信息写在文件里就行了。Windows 继承了 DOS 的遗产，系统里有多个文件系统——每个盘符（`C:\`、`D:\` 等）都是一个独立的文件系统，每台机器上有哪些盘符是不确定的，软件开发者无法假定自己的配置文件写在哪里是一定安全的，所以才有了注册表这么个东西。

**Comment by jiangsc17** [comment]
太感谢你了老师 我感觉收获非常多
