### ISSUE TITLE
Python 安装失败 

### ISSUE THREAD

**Issue by June0629** [neolee/wop-ecnu-pub#28]
![python安装失败](https://user-images.githubusercontent.com/61927368/76816456-3df44800-683b-11ea-98c8-5be4c6db5580.PNG)

**Comment by June0629** [comment]
PS C:\Users\24633>  scoop install python@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.8.2)
WARN  Attempting to generate manifest for 'python' (3.7.4)
Autoupdating python
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
Found: md5:a702b4b0ad76debdb3043a583e563400 using Extract Mode
Writing updated python manifest
Installing 'python' (3.7.4) [64bit]
Loading python-3.7.4-amd64.exe from cache
Checking hash of python-3.7.4-amd64.exe ... ok.
Loading uninstall-pep-514.reg from cache
Checking hash of uninstall-pep-514.reg ... ok.
Loading python-3.8.2-amd64.exe from cache
Checking hash of python-3.8.2-amd64.exe ... ok.
Running pre-install script...
Get-Content : 找不到路径“C:\Users\24633\scoop\apps\python\3.7.4\install-pep-514.reg”，因为该路径不存在。
所在位置 行:4 字符: 16
+     $content = Get-Content "$dir\$_"
+                ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\24633\...all-pep-514.reg:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by neolee** [comment]
分别执行下面的各个命令看看结果是啥：

```powershell
$PSVersionTable.PSVersion.Major
$env:Path

scoop checkup
scoop update
scoop list
```

**Comment by June0629** [comment]
> 分别执行下面的各个命令看看结果是啥：
> 
> ```powershell
> $PSVersionTable.PSVersion.Major
> $env:Path
> 
> scoop checkup
> scoop update
> scoop list
> ```

已装好 谢谢老师
