### ISSUE TITLE
关于 for 的问题

### ISSUE THREAD

**Issue by KGBMAX** [neolee/wop-ecnu-pub#29]
python 中for 循环除了使用i in range() 以外还可以使用 for item in 方式（迭代器）但是在C++中，迭代器数据类型是 iterator 类型，python 中却直接显示为迭代内容的数据类型, 想请老师解释一下其机制。
<img src="https://user-images.githubusercontent.com/39229322/76841819-474dd680-6874-11ea-99a8-3be53750a9b6.png" alt="image-20200316134711374" style="zoom:10%;" />

**Comment by neolee** [comment]
不是很理解你的问题。

`for item in col:` 这个结构里，`col` 是被迭代的容器，按照 Python 的机制，必须是 iterable object（也就是实现了 `__iter__()` 和 `__next__()` 两个方法的对象），至于具体类型并无限制；而 `item` 是从 `col` 中取出的各个元素，是什么类型都可以，甚至可以是不同的类型。
