### ISSUE TITLE
python 安装

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#3]
老师，我之前安装过python，但我现在按照要求在conEmu安装python时出现了错误。
![微信图片_20200304133357](https://user-images.githubusercontent.com/61767345/75848524-6c2a5e80-5e1d-11ea-9030-2970daec7305.jpg)
我已尝试scoop自检，但无法完成。
![微信图片_20200304134510](https://user-images.githubusercontent.com/61767345/75848867-6719df00-5e1e-11ea-882a-748dbce14188.jpg)

**Comment by neolee** [comment]
scoop checkup 的问题，可以尝试打开一个管理员权的 PowerShell (Admin) 命令行窗口来运行那个命令，应该就可以成功。

安装 Python 失败是因为网络不稳定，可以换网络或者换时间重试，或者尝试网络代理。

**Comment by unicorn-xia** [comment]
老师，以前按过python，现在要重新按吗；以前也按过anaconda，要重新按Jupyter Lab吗

**Comment by neolee** [comment]
这个问题我昨天上课不是讲了么？如果你对环境有把握，用你熟悉的没问题，只要有符合要求的 git 和 Python，然后按照 [指南](https://github.com/neolee/wop-ecnu-pub/blob/master/x2-students-book.md) 准备好 Jupyter Lab 和学习用书，就可以开始学了。

如果对环境不太有把握，最好按照课程里的指南来做，这样大家一致，以后遇到问题也比较容易得到老师和同学的帮助。

**Comment by unicorn-xia** [comment]
老师，我上网搜了一下有关网络代理方面的知识，网上推荐了一些软件，请问老师有推荐的软件或IP地址吗

**Comment by limj0825** [comment]
这个可以问下周围的朋友们，公开讨论不太好。。。

**Comment by unicorn-xia** [comment]
问题解决了，用网络代理换个IP地址就好啦
