### ISSUE TITLE
质数问题的缩进

### ISSUE THREAD

**Issue by LauraWen** [neolee/wop-ecnu-pub#31]
老师好：

![image](https://user-images.githubusercontent.com/46390542/77404955-7375d400-6ded-11ea-8463-fcd222c9ad69.png)

在实现是否质数的这个问题中，```else:```的缩进为什么是和```for :```保持一致呢？
我之前在试的时候发现，当```else:```的缩进和```if :```保持一致的时候，就不会出现2是否为质数的判断结果。

**Comment by neolee** [comment]
你好像是第一个响应号召提问题的，所以奖励你一点"秘笈"。

> 在写 Python 程序前，先用普通的中文写清楚自己的思路。

当然了，写的时候脑子想想尽量靠向我们今天讲的"顺序、选择和循环"三种结构会更好。

比如我看你的代码，大概能猜出你的素数验证逻辑，大致是这样的：

```
取 2~n 的所有整数，对其中每一个 i 做：
    检查 i 是否能整除 n，如果整除了，说明 n 是合数，余下的不必再试
    如果 i 不能整除 n，则继续下一个 i

如果上述测试全部完成后，没有任何一个 i 能整除 n，则 n 是素数
```

仔细想想，你的思路是不是这样？

如果是的话，再想想，你的循环体里面的那两条逻辑：
```
    检查 i 是否能整除 n，如果整除了，说明 n 是合数，余下的不必再试
    如果 i 不能整除 n，则继续下一个 i
```
应该翻译成什么样的 Python 代码呢？肯定不应该是下面这个吧：
```python
if n % i == 0:
    print(n, `是合数`)
    break
else:
    print(n, `是素数`)
```

那么 `for...else` 又是什么意思呢？这个我上课没讲，因为不是必须用到，而且稍微有点复杂。其实 `for` 后面是可以跟个 `else` 分支的，意思是“如果 for 循环正常循环完毕而不是 break 退出的话则运行 else 后面的内容”。所以这个结构恰好和上面的白话逻辑是吻合的。

有了上面的这些解释，你现在能解决自己的问题了么？

**Comment by LauraWen** [comment]
谢谢老师！！我现在理解了： "判断它是一个素数”应该是发生在循环结束后的。
