### ISSUE TITLE
字典中的 key 的选取问题

### ISSUE THREAD

**Issue by ecnu10195000414** [neolee/wop-ecnu-pub#32]
![QQ图片20200325092622](https://user-images.githubusercontent.com/61929330/77492190-dceff400-6e7a-11ea-8138-b7b81698a9dc.png)
我分别尝试用"一月"和一月作为一个字典的key，但前者失败了，后者成功了，而type(一月）显示出错，我很疑惑一月到底是什么。而且为什么我用dict(zip(L1,L2))的方法就成功了呢。麻烦老师了。

**Comment by neolee** [comment]
我们的教材还没有涉及到数据容器，你这些代码和知识是从哪里来的呀？

既然问到了，可以给你偷跑几个知识点：

1. Python 里 dict 的 key 可以是 immutable 的任何类型（几乎），比如 int、float、str、bool 等，甚至数据容器里的 tuple 类型的值也可以做 key。所以 `'一月'` 这个字符串做 key 没问题，而且经常就这么用的。

2. `zip()` 这个函数把两个 list 合并起来，输出一个 iterable object，里面是若干 tuple，每个 tuple 里是一对值；然后可以用 `dict()` 把这个 iterable 转换为 dict，每个 tuple 里前一个值做 key，后一个值做 value。所以你对 `zip` 的使用也没啥问题，`'一月'` 这个字符串做了 key，`5` 这个整数做了值。但这背后的原理机制，可能你要要等 S2 学完 iterable 和几种数据容器后才能真正理解。

3. `dict` 的 `update()` 方法，不是你这么个用法（实际上你可能也不知道自己在怎么用，前后都不一样）。这个方法要求一个 iterable 作为输入，实际上这个输入的 iterable 要么是个 dict，要么是类似前面讲的一组 tuple，总之里面要包含一组 key-value 对，然后 `update()` 方法用这个 iterable 里的 key-value 对来更新自己的内容。所以下面的代码才是正确姿势：

```python
l1 = ['一月', '二月', '三月']
l2 = [3, 4, 9]

d = dict(zip(l1, l2))
print(d)

d.update({'三月':12, '四月':16})
print(d)

d.update([('三月', 15), ('五月', 20)])
print(d)
```

4. Python 允许用中文做变量名（实际上任何 Unicode 字符都可以），但非常不推荐这么做，会有很多坑，现在阶段学习正确的姿势更重要。学东西就要学地道的，偏门是你熟练之后拿来玩的。你的 `type(一月)` 出错，就是 Python 把 `一月` 作为一个变量，然后没发现它之前有出现过。

5. `d.update(一月=3, 二月=5)` 这样的写法是可以的，因为这也是一种特殊的 iterable，实质上等价于下面的代码：

```python
input = (('一月', 3), ('二月', 5)) # 这是一个包含一组 tuple 的 tuple
d.update(input)
```

我是不会推荐初学者先去学 `d.update(一月=3, 二月=5)` 这种写法的，因为容易迷惑。先掌握本质很重要。

最后，往前跑我是鼓励的，但要建立在扎实的基础上，前面先得真搞明白了，才能往后跑，你觉得呢？

**Comment by ecnu10195000414** [comment]
谢谢老师，我的公共必修课里有python，所以这个问题是我在做那门课的作业中遇到的，我上学期学过dict，但几个月过去了已经有点遗忘，书本由于疫情原因留在学校里拿不到，无法复习相关知识，为了做这个作业就尝试用记忆中的几个dict的方法，有的成功了有的没成功，就来问问老师那几个没成功的原因。

**Comment by neolee** [comment]
那么你现在搞明白了么？

**Comment by ecnu10195000414** [comment]
老师不好意思，我还是不太明白为什么d.update(一月=5)是可以的，而d.update("一月"=5)会报错

**Comment by ecnu10195000414** [comment]
老师不好意思，我还是不太明白为什么d.update("一月"=5)会报错

**Comment by neolee** [comment]
嗯，这也是为什么我说我不会推荐大家去用 `d.update(一月=3, 二月=5)` 这种写法的原因，这种写法实际上是利用了 Python 的函数输入参数定义里的一些高级语法，我们在课程 S2 开始阶段会讲。

在这个写法中，等号前面的东西叫做输入参数的“keyword”，这个 keyword 不能是任何普通的值或者表达式（也就是说不能是 `"一月"` 这样的字符串），而必须是不带引号的一个名字，然后 `update` 函数就自动把它用作 key（拥有 str 类型），而把等号右边的值用作 value。

**Comment by ecnu10195000414** [comment]
我懂了，谢谢老师。
