### ISSUE TITLE
判断素数问题

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#33]
老师，我尝试定义一个函数 ` isPrime ` 用于判断，但我第一次尝试的时候，代码如下
```python
def isPrime(num):
    from math import sqrt
    num = int(input('请输入一个数'))
    for i in range(2, int(sqrt(num)) + 1):
        if num % i == 0:
            return False
    else:
        return True
if isPrime(num):
    print(num,'是素数')
else:
    print(num,'不是素数')
```
显示
```python
NameError: name 'num' is not defined
```
可是我明明定义了 ` num ` 就是用户 ` input ` 的内容
我百思不得其解，我做了很多尝试，最后一次成功了，如下
```python
def isPrime(num):
    from math import sqrt
    for i in range(2, int(sqrt(num)) + 1):
        if num % i == 0:
            return False
    else:
        return True
num = int(input('请输入一个数'))
if isPrime(num):
    print(num,'是素数')
else:
    print(num,'不是素数')
```
把 ` num = int(input('请输入一个数')) ` 放到函数定义外面就成功了，这是为什么呢？
我自己觉得可能是函数的变量到外面就失效了，是这个原因吗，我不是很明白。
谢谢老师！

**Comment by neolee** [comment]
恭喜你，你问了一个未来的问题。

以后我们会讲变量的作用域（scope）问题。函数内使用的变量（包括输入参数）属于局部变量（local var），而函数外的属于全局变量（global var）。这两个 scope 中的变量是完全隔离的，即使名字一样也不是一个东西。

你的后一个版本比前一个好很多，最大的好处是做到了责任分离。函数 `isPrime()` 就管判断输入的整数是不是素数，别的都不管；而函数以外的代码负责处理用户的输入输出问题，结构上要清晰很多，而且 `isPrime()` 函数就有了复用的可能，以后甚至可以用在网页上，你甚至可以写个线上的服务判断某个数是不是素数，可以直接拿着个函数来用，因为它不依赖于具体的用户交互形式，是个干净纯粹的函数。

另外有几点提醒：

1. 函数的命名：Python 通常采用小写单词作为变量和函数名，多个单词之间用下划线分开，所以那个函数名最好叫做 `is_prime`。学东西就要学地道，遵循一个编程语言的习惯有很多好处。

2. 程序中可以引入适当的空行。

3. `import` 语句习惯上放在源文件的最开始，而不是放在代码中间，虽然后者也完全合规，但管理起来会麻烦，放在前面可以一目了然知道你这个程序依赖哪些外部的代码。

4. 第一个版本的代码，即使没有你后面发现的问题，也比较不好，你想想，`num` 是这个函数的输入参数，也就是调用这个函数的时候传进来的一个值，然后你在函数里面把它的值改了，改成用户键盘输入的值，那将它作为输入参数的意义何在呢？是不是完全可以不用这个输入参数？

最后，`range(2, int(sqrt(num)) + 1)` 这个优化不错，比 `range(2, n)` 效率高多了。

**Comment by unicorn-xia** [comment]
谢谢老师，我觉得我终于理解到了函数的重要性了。
