### ISSUE TITLE
闰年

### ISSUE THREAD

**Issue by ecnu-gjy** [neolee/wop-ecnu-pub#34]
<img width="581" alt="屏幕快照 2020-03-25 下午7 29 46" src="https://user-images.githubusercontent.com/61778175/77532162-4863b100-6ecf-11ea-9859-d1d24f4e5ad5.png">
为什么第一个没办法运行呢？

**Comment by neolee** [comment]
`try` 后面需要一个配套的 `except` 子句。

另外，你这个闰年的规则似乎不对呀。

**Comment by ecnu-gjy** [comment]
好的，谢谢老师，闰年的规则缺了一条，我先试了一下🙈
