### ISSUE TITLE
关于类变量

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#35]
老师，我自己尝试了一下今天上课讲的类变量，但是结果好像与老师演示的不太一样，如下：
<img width="217" alt="捕获" src="https://user-images.githubusercontent.com/61767345/78007250-9ade1b00-7370-11ea-96b2-2a1b5cc7caa0.PNG">
请问为什么呢，谢谢老师！

**Comment by neolee** [comment]
是这样的，你只要执行过 `a.kind = ...` 这样的代码，`a.kind` 就和 `Animal.kind` 脱钩，变成两个完全没关系的东西了——前者是一个实例变量，后者是类变量。

如果你的某个对象从来没给类变量赋过值，那么用这个对象去访问类变量的时候会自动理解为访问 `Animal.kind`。

**Comment by unicorn-xia** [comment]
噢噢，我懂了，谢谢老师！
