### ISSUE TITLE
用 scoop 下载 git 遇到的问题

### ISSUE THREAD

**Issue by siriuszza** [neolee/wop-ecnu-pub#36]
1.scoop install git 需要翻墙不然卡0%（已解决）
2.如图
![image](https://user-images.githubusercontent.com/61924224/78015376-e77b2380-737b-11ea-911f-a763c9dc9b94.png)

**Comment by neolee** [comment]
你执行 `scoop checkup` 是什么结果？

你的 Windows 版本为何？
