### ISSUE TITLE
busybox 需要安装吗？

### ISSUE THREAD

**Issue by xaycq** [neolee/wop-ecnu-pub#37]
我在安装busybox时一直出现错误，但是不影响使用，查资料说安装好后比较方便管理，如何才能安装好呢？

**Comment by neolee** [comment]
不是必须的。

如果想安装而遇到问题，至少要告诉我们遇到什么问题，才好判断啊。

**Comment by xaycq** [comment]
具体错误如下：

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://frippery.org/files/busybox/busybox-w64-FRP-3329-gcf0fa4d13.exe#/busybox.exe
    referer=https://frippery.org/files/busybox/busybox-w64-FRP-3329-gcf0fa4d13.exe#/
    dir=C:\Users\admin\scoop\cache
    out=busybox#3329-gcf0fa4d13#https_frippery.org_files_busybox_busybox-w64-FRP-3329-gcf0fa4d13.exe_busybox.exe

ERROR & 'C:\Users\admin\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\admin\scoop\cache\busybox.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=16 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8204 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=busybox%403329-gcf0fa4d13%3a+download+via+aria2+failed

**Comment by xaycq** [comment]
PS C:\Users\admin> scoop install busybox
Updating Scoop...
Updating 'main' bucket...
 * 35959acb ffmpeg-nightly: Update to version 20200401-afa5e38           15 minutes ago
Updating 'versions' bucket...
Scoop was updated successfully!
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'busybox' (3329-gcf0fa4d13) [64bit]
Starting download with aria2 ...
Download: [#887883 0B/0B CN:1 DL:0B]
Download: [#887883 0B/0B CN:1 DL:0B]
Download: [#887883 0B/0B CN:1 DL:0B]
Download: [#887883 0B/0B CN:1 DL:0B]
Download: [#887883 0B/0B CN:1 DL:0B]
Download: [#887883 0B/0B CN:1 DL:0B]
Download: 04/01 18:17:30 [ERROR] CUID#8 - Download aborted. URI=https://frippery.org/files/busybox/busybox-w64-FRP-3329-gcf0fa4d13.exe#/busybox.exe
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://frippery.org/files/busybox/busybox-w64-FRP-3329-gcf0fa4d13.exe
Download:   -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: 鐢变簬鍚婇攢鏈嶅姟鍣ㄥ凡鑴辨満锛屽悐閿€鍔熻兘鏃犳硶妫€鏌ュ悐閿€銆?
Download: (80092013)
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 887883|ERR |       0B/s|C:/Users/admin/scoop/cache/busybox#3329-gcf0fa4d13#https_frippery.org_files_busybox_busybox-w64-FRP-3329-gcf0fa4d13.exe_busybox.exe
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://frippery.org/files/busybox/busybox-w64-FRP-3329-gcf0fa4d13.exe#/busybox.exe
    referer=https://frippery.org/files/busybox/busybox-w64-FRP-3329-gcf0fa4d13.exe#/
    dir=C:\Users\admin\scoop\cache
    out=busybox#3329-gcf0fa4d13#https_frippery.org_files_busybox_busybox-w64-FRP-3329-gcf0fa4d13.exe_busybox.exe

ERROR & 'C:\Users\admin\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\admin\scoop\cache\busybox.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=16 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8204 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=busybox%403329-gcf0fa4d13%3a+download+via+aria2+failed
PS C:\Users\admin>

**Comment by neolee** [comment]
网络问题，如果换网络或者代理还不行的话，可以先搁着，并非必需。
