### ISSUE TITLE
super 的用法

### ISSUE THREAD

**Issue by ECNU2036** [neolee/wop-ecnu-pub#38]
在class Husky (Dog) 的例子中，super的写法是下面这样的吗？

```python
class Husky (Dog)
      def__init__(self.name)
      super().self.name=name
      self.habitat='Arctict'
```

**Comment by neolee** [comment]
正确的写法是：

```python
class Husky(Dog):
    def __init__(self, name):
        super().__init__(name)
        self.habitat = 'Arctic'
```

这部分语法是 Python 里比较迷惑的，可以这么理解：

1. 当我们要使用一个对象的属性时要用 `obj.xxxx` 这样的语法，调用一个对象的方法则是 `obj.do_xxx(a, b)` 这样的语法，也就是说，先要有个变量 `obj`，然后在它后面加个点 `.` 然后接属性的名字后者函数调用，就可以了。

2. 类是未来生产对象的模板，那我们在类定义里面要使用对象属性和方法怎么办呢？类只是个模板，还没有产生具体对象的情况下，怎么表示这个对象呢？所以 Python 引入了特殊的关键字 `self`，用它来表示“这个类将要产出的对象实例自己”。所以在类定义里要提前引用未来要产生的对象，就用 `self`，后面可以跟属性和方法的调用。

3. `super()` 和 `self` 作用类似，它们都代表这个类未来要生产的对象，只不过它代表父类版本的对象，比如上面代码中的 `super().__init__(name)` 代表“用 name 的值作为参数调用父类版本的 __init__ 方法”。

最后，你的代码的问题包括：
* `def __init__` 方法定义的那一行，`def` 后面缺空格，参数也不对：有两个参数，第一个是 self，第二个是 name；
* `def __init__` 下面的代码段没有正确缩进；
* `super()` 的使用不对，见上面的说明；
* 在这里要引用 Python 代码可以用下面的格式，就能保持缩进格式，还会有语法颜色显示：
 <pre>
```python
<把你的代码粘贴到这里>
```
</pre>
