### ISSUE TITLE
函数之后一定要加括号吗

### ISSUE THREAD

**Issue by ECNU2036** [neolee/wop-ecnu-pub#39]
```python
print(a.voice())
Print(a.bark())
```
voice 和 bark 之后都有括号。
```python
print(a.name)
print(a.kind)
```
name 和 kind 之后没有括号，是因为这两者有什么区别吗?

**Comment by neolee** [comment]
首先，参见我对你另一个问题的回答，了解如何正确的在 issue 里贴 Python 代码 #38 

然后，你第一段代码里第二行大小写有误，应该是 `print`。

最后，
* `a.name` 是一个变量，或者叫属性，指向一个字符串类型的值。
* `a.voice` 也是一个变量，或者属性，指向一个函数；而 `a.voice()` 是调用这个函数的语法。
