### ISSUE TITLE
安装和运行 Jupyter Lab 出现问题

### ISSUE THREAD

**Issue by ECNUACRush** [neolee/wop-ecnu-pub#4]
老师。我在安装Jupyter lab的时候出现问题：之前的步骤都已经顺利完成
这是第一次安装：
![~SBJCNW7W5)~INMSS%ER )O](https://user-images.githubusercontent.com/49430264/75860916-8ec97100-5e37-11ea-9cce-a923f0743e71.png)

最后没有安装成功，接着第二次尝试 `pip3 install jupyterlab` 
![@SXG0MGWK_%VX2A0A{H2}TU](https://user-images.githubusercontent.com/49430264/75860983-abfe3f80-5e37-11ea-8965-a3d2304751aa.png)

同样没有安装成功，百度查了一下说是网络问题导致超时，推荐使用` pip --default-timeout=100 install jupyterlab`进行安装。尝试了如下：
![R)FGS}YQ44 R BI1STDJ}9P](https://user-images.githubusercontent.com/49430264/75861198-039cab00-5e38-11ea-8ab2-f5414d8ecc57.png)
最后也没有安装成功：
![LWB5%UKR`1UJLLIUCDG{35M](https://user-images.githubusercontent.com/49430264/75861262-1dd68900-5e38-11ea-8654-3cc7ff51049e.png)

**Comment by neolee** [comment]
这个是网络问题，不过到了这一步就好办了，因为 PyPi 有很好的国内镜像站点，比如清华的这个：

https://mirror.tuna.tsinghua.edu.cn/help/pypi/

按照这里说的操作，改用这个镜像站点，一般都可以顺利下载的。

**Comment by ECNUACRush** [comment]
谢谢老师！问题解决了。
有相同问题的同学可以参考使用以下命令：
`pip install -i https://pypi.tuna.tsinghua.edu.cn/simple jupyterlab`
