### ISSUE TITLE
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.

### ISSUE THREAD

**Issue by ArixLi** [neolee/wop-ecnu-pub#40]
after appearing this waning, i use "python -m pip" to install simpleeval, however, the shell shows "No module named 'simpleeval'".
So how to deal with it?

**Comment by neolee** [comment]
我想你的 Python 和 pip 的版本都太老。

你的操作系统及版本？

以及运行下面命令的结果？

```shell
which python
which python3
python -V
python3 -V
pip -V
pip3 -V
```

**Comment by ArixLi** [comment]
谢谢老师，我在anaconda虚拟环境中成功了。
