### ISSUE TITLE
字符串 in 的用法

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#42]
<img width="187" alt="捕获" src="https://user-images.githubusercontent.com/61767345/78748089-ad260d80-799d-11ea-951e-75982ef8e93c.PNG">
老师，为什么两次执行结果不一样呢？

**Comment by neolee** [comment]
嗯，好问题，`in` 这个操作符我们没有讲过，所以自己去玩玩就会发现类似这样的问题，但这就是学习的过程。

因为 `in` 这个操作符可以用于不同的数据类型，用于字符串和用于列表的含义有小小区别。

* `"n't" in "couldn't"` 这个是判断一个字符串是不是另一个字符串的子串，只要后面的字符串里包含完整的 `"n't"` 子串，就会返回 `True`，反之则返回 `False`。
* `"n't" in a.split()` 中，`in` 后面的 `a.split()` 是一个列表（数组），这时候 `in` 是判断前面的 `"n't"` 是不是后面列表里的一个元素，在你的例子里，`a.split()` 的值是 `['I', "couldn't", 'be', 'better']`，里面四个元素都不是 `"n't"`，所以就返回 `False` 了。
