### ISSUE TITLE
在 VS code 中尝试 debug 时发现 module 找不到

### ISSUE THREAD

**Issue by jingluo-star** [neolee/wop-ecnu-pub#43]
![debug](https://user-images.githubusercontent.com/61736909/78751280-799ab180-79a4-11ea-8fc2-ac965935323e.PNG)

老师，我已经检查过是否装了 `termcolor`
  
![pip](https://user-images.githubusercontent.com/61736909/78751083-232d7300-79a4-11ea-98f4-8ecbc411b42d.PNG)

同时我尝试了用 ctrl+shift+P 切换了我电脑上所有可用的 python 解释器，都显示找不到     `termcolor`，不知道问题出在哪了。

同时，我用 # 隐去此句语句后，发现其他包也不行，只有 python 内置的包没有报错，为何用 debug 功能会出现这样的情况呢？

![debug2](https://user-images.githubusercontent.com/61736909/78751632-2d03a600-79a5-11ea-9318-a8ceef70ceed.PNG)

**Comment by jingluo-star** [comment]
另外，我不用 debug 功能，在 VS code 中开 terminal 自己 run 这个 python 文件一切正常。

**Comment by neolee** [comment]
这个情况很奇怪，我这里没有遇到。比较大的可能性是：你的系统里安装的 Python 环境不够标准，所以 Visual Studio Code 无法正常识别它。

从你的命令行提示看，你的 Python 环境不是按照我给出的指南安装的吧？

**Comment by jingluo-star** [comment]
开始时是按照你的步骤装的所有内容，只是之前在其他地方装过 python 之前老的版本
![debug3](https://user-images.githubusercontent.com/61736909/78792573-da95aa00-79e3-11ea-8aed-9d5ffb02b9b9.png)

**Comment by jingluo-star** [comment]
好吧，我又试了下。这次用那个F盘的 python 3.6.6 解释成功了。
不过有两个问题：①为啥我两个版本它偏偏就要往F盘里装包，是因为我那个 python 版本先装吗，能改到我这个3.7.4版本里吗，还是说要卸载那个老的，卸载会不会出问题。
②为啥包都在这个F盘的版本里，我用3.7.4版本的 python 解释器却能成功运行，是因为我 `pip install ...` 都是在命令行里执行的原因吗，好像解释不通。

**Comment by neolee** [comment]
这个问题，你可以试试 Wiki 里给出的自检方法，运行下面的这些命令：

```powershell
$env:Path

which python
python -V
pip -V
```

从这些信息里你可以自己思考下，为什么会有你遇到的问题。

最后，如果希望以后少些麻烦，建议你清理一下多余的 Python 环境，只保留按照指南安装的。否则出现类似问题的几率不低。

**Comment by jingluo-star** [comment]
好的，谢谢老师
