### ISSUE TITLE
用 try except 异常处理会有 None

### ISSUE THREAD

**Issue by Joestarc** [neolee/wop-ecnu-pub#44]
<img width="494" alt="屏幕快照 2020-04-08 下午5 43 18" src="https://user-images.githubusercontent.com/61925101/78769994-9e9d1d80-79c0-11ea-9149-79ebc1e8f74d.png">
<img width="945" alt="屏幕快照 2020-04-08 下午5 44 20" src="https://user-images.githubusercontent.com/61925101/78770002-a1980e00-79c0-11ea-92ab-cf52480c17cd.png">
请问None是怎么出来的，怎么才可以不显示None呢？

**Comment by neolee** [comment]
思考一下你最后一行 `print(self.say(...))` 它会打印出什么，为什么？

**Comment by LauraWen** [comment]
这里是因为有NameError和ZeroDivisionError才会执行  ```print(self.say(...))``` 这句话吗？但是是哪个地方输出了None呢？

**Comment by neolee** [comment]
就是 `print(self.say(...))` 这一句输出的呀，你想想为啥？

**Comment by Joestarc** [comment]
> 就是 `print(self.say(...))` 这一句输出的呀，你想想为啥？

是因为say这个函数里面最后用的print而不是return，所以没有返回值才显示的none吗

**Comment by Joestarc** [comment]
试了一下好像就是因为print里面的函数没有返回值就会打印出None...最后不用print，直接用self.say（）就可以了

**Comment by neolee** [comment]
对头。

1. `self.say()` 里就有 `print()` 调用，会输出了，所以不需要在外面再 `print()`。
2. Python 的函数必须有一个返回值，如果你没有写，那么相当于在函数定义的最后有个 `return None`。

下面两次课就会讲这些。
