### ISSUE TITLE
使用 cmd 终端打开文件 format 格式的颜色显示为乱码请问如何解决？

### ISSUE THREAD

**Issue by ArixLi** [neolee/wop-ecnu-pub#45]

**Comment by neolee** [comment]
因为 cmd 终端不支持这个方法啊，你看我什么时候用过 cmd 终端或者在教材中让大家用 cmd 终端？

在 Windows 下，环境配置指南推荐使用的是 ConEmu 这个命令行界面，或者你使用 Microsoft 推出的新版 Terminal（目前还是预览版本）也可以；或者用 Visual Studio Code 里面那个 Terminal 通常也没问题（但有过个别同学在这里遇到过问题）。

最后，问题需要更具体的描述，最好有个截图什么的，不然我只好猜你大概是碰到啥问题……

**Comment by ArixLi** [comment]
好的，谢谢老师
