### ISSUE TITLE
pip 和 jupyter 问题

### ISSUE THREAD

**Issue by 23spiteful** [neolee/wop-ecnu-pub#46]
PS C:\Users\74092> workon jupyter
workon : 无法将“workon”项识别为 cmdlet、函数、脚本文件或可运行程序的名称
。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ workon jupyter
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (workon:String) [], Command
   NotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\74092> pip install termcolor
Traceback (most recent call last):
  File "d:\python3.7.4\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python3.7.4\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python3.7.4\Scripts\pip.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'pip'

**Comment by neolee** [comment]
1. 你不需要执行 `workon` 命令，那个是我的系统里采用了虚拟 Python 环境才需要的；对于初学者来说，所有的事情都在安装的 Python 系统里做就好了。

2. 第二个错误，是你的 Python 环境有问题，里面没有装 pip。从信息来看，你的 Python 环境并不是按照我的配置指南安装的吧？

**Comment by 23spiteful** [comment]
python是自己下的，但我也装了pip呀
PS C:\Users\74092> which pip
D:/python3.7.4/Scripts//pip.exe
那有补救措施吗？还是重新安装？

**Comment by 23spiteful** [comment]
PS C:\Users\74092> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\74092> scoop
& : 无法将“C:\Users\74092\scoop\shims\..\apps\scoop\current\bin\scoop.ps1
”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如
果包括路径，请确保路径正确，然后再试一次。
所在位置 C:\Users\74092\scoop\shims\scoop.ps1:3 字符: 71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args
  ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\74092\...t\bin\sc
   oop.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
之前不是这样。。。

**Comment by neolee** [comment]
你展示的 pip.exe 只是个封装脚本，真正运行还是要用 Python 解释器去运行一个叫 pip 的模块，而你的解释器找不到这个模块所以出错了。

因为你没按照要求准备环境，我也不知道你怎么安装的 Python，更无法在我的系统里尝试，所以没法给你准确的建议。课程伊始我就说了，如果不按标准来也可以，我会假定你知道自己在做什么，有能力解决自己可能遇到的问题。

最后，也许可以试试 `python -m ensurepip`。

**Comment by 23spiteful** [comment]
pip解决了，但我现在是不是没法再用准备环境的操作重新安装了
PS C:\Users\74092> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\74092> scoop
& : 无法将“C:\Users\74092\scoop\shims\..\apps\scoop\current\bin\scoop.ps1
”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如
果包括路径，请确保路径正确，然后再试一次。
所在位置 C:\Users\74092\scoop\shims\scoop.ps1:3 字符: 71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args
  ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\74092\...t\bin\sc
   oop.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
这个就不清楚了，似乎 scoop 没装好，删了重装。

不过你目前最需要做的选择是：到底用你自己安装的环境还是用推荐指南的方法，无论怎么选，不要混用，对初学者来说，多个系统混杂带来的麻烦是难以解决的。
