### ISSUE TITLE
我重装了scoop，下载 git 就一直卡在这

### ISSUE THREAD

**Issue by 23spiteful** [neolee/wop-ecnu-pub#47]
PS C:\Users\74092> scoop install git
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [==============================================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\19.00
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (19.00) was installed successfully!
Installing 'git' (2.26.0.windows.1) [64bit]
PortableGit-2.26.0-64-bit.7z.exe (41.1 MB) [=========>                                 ]  23%

**Comment by neolee** [comment]
网络问题。
