### ISSUE TITLE
请问要用什么指令让程序按顺序分两次返还两句话

### ISSUE THREAD

**Issue by 1773798978** [neolee/wop-ecnu-pub#51]
![1586617749(1)](https://user-images.githubusercontent.com/61928538/79047502-94418480-7c49-11ea-873d-7fdda725bc19.png)
![1586617760(1)](https://user-images.githubusercontent.com/61928538/79047506-9572b180-7c49-11ea-84cc-2195fa7f076a.png)

如图，我想让程序按顺序说出两句话，但程序只能说出其中一句，而且并没有规律

**Comment by neolee** [comment]
每次函数调用只会有一个返回值，函数执行到任何一个 return 就返回了，所以你写两个 return 的话，只有第一个会有用。

你的需求其实是希望返回一个包含多行文本的字符串，去自学一下第十章（p1-a）就有答案了。

**Comment by 1773798978** [comment]
> 每次函数调用就会有一个返回值，函数执行到任何一个return就返回了，所以你连着写两个return的话，只有第一个会有用。
> 
> 你的需求其实是希望返回一个包含多行文本的字符串，去自学一下第十章（p1-a）就有答案了。
那我如果想让它返回两句话之间有时间间隔，可以实现吗

**Comment by 1773798978** [comment]
那如果我想让它返回两句话之间有时间间隔，可以做到吗

**Comment by 1773798978** [comment]
老师，那如果我想它更拟人化一点。让它在返还两句话之间有时间间隔，可以做到吗？

**Comment by neolee** [comment]
Emmm，这个想法的话，可以做到，最简单的办法是让 `_say()` 方法可以说说多句话（目前是固定一句，哪怕多行也是一次说出来的），这样的话它的参数可能要从字符串改为字符串的列表——建议你学完下一阶段的数据容器再来做这个改动吧！

**Comment by 1773798978** [comment]
谢谢老师！
