### ISSUE TITLE
使用 termcolor 时出现乱码

### ISSUE THREAD

**Issue by Sakurai-Minami** [neolee/wop-ecnu-pub#52]
我在使用termcolor的colored时，最终显示的代码无法上色，但在首尾有乱码。
为方便观察，测试语句如下。
![image](https://user-images.githubusercontent.com/61926093/79053513-91a65580-7c70-11ea-9258-880050ffb1c3.png)
终端上显示已经安装好了termcolor。
![E131F72A2F47AF10D88F9B0579888989](https://user-images.githubusercontent.com/61926093/79053789-69b7f180-7c72-11ea-915b-a8a299ba80f8.png)
我也考虑到可能存在pip的位置装错的问题，测试之后似乎是正确的。
![image](https://user-images.githubusercontent.com/61926093/79053893-5bb6a080-7c73-11ea-9b0c-48e18e394a09.png)
我在网络上发现了与我有相同问题的人，但我没有获得有帮助的解决方案。
https://www.it1352.com/533549.html

请问老师还有可能是什么错误？

**Comment by neolee** [comment]
你为什么要用 Python Shell，你用正常的 terminal 就不会有问题，这个上色是需要命令行界面支持标准规范才行的，Python Shell 只是个残缺的命令行界面，没有程序员会用那个。

如果真准备学编程，还是按照配置指南来吧。

**Comment by Sakurai-Minami** [comment]
好的老师。
我刚才按配置指南的方法搬过去了，问题解决了，谢谢老师。
