### ISSUE TITLE
无法保存 python 源文件

### ISSUE THREAD

**Issue by ECNU2036** [neolee/wop-ecnu-pub#53]
![image](https://user-images.githubusercontent.com/61863257/79063161-7ff59a00-7cd2-11ea-8732-57e78b5d9279.png)

**Comment by neolee** [comment]
你应该使用 Visual Studio Code 而不是 Jupyter Lab 来编辑、保存和运行 `.py` 文件。

你有听周二讲解的课吗？

**Comment by ECNU2036** [comment]
老师，我在Visual Studio Code 因该怎么保存呀

**Comment by neolee** [comment]
去看周二上课的录像。
