### ISSUE TITLE
KeyError 如何解决

### ISSUE THREAD

**Issue by 1773798978** [neolee/wop-ecnu-pub#55]
![1586711678(1)](https://user-images.githubusercontent.com/61928538/79075310-a0e6db00-7d24-11ea-8966-810e19ae1838.png)
![1586711700(1)](https://user-images.githubusercontent.com/61928538/79075312-a3493500-7d24-11ea-876b-1a7c48e01f43.png)
![1586711724(1)](https://user-images.githubusercontent.com/61928538/79075313-a512f880-7d24-11ea-8e07-4319d3577e2f.png)
如图，我随便输入了一串字符来测试异常处理的效果，但出现了一个KeyError。我将KeyError加入到except后的括号里也没有解决这个问题。

**Comment by neolee** [comment]
首先，不要对同一个问题发多个 issue，如果发现自己发的标题或者内容有问题，直接编辑（Edit）就好了。Closed Issue 也可以重新打开。

如果你要捕获 KeyError 这种异常，把它包含在`except` 子句后面就可以了，你说包含了它也不行，这应该是不会的，你再试试，是不是有别的问题。

另外，我建议你把 `try…except` 放在 `_think()` 方法中，异常捕获不要范围太大，应该针对你知道有可能出异常的具体代码块。

最后，怎么能在给用户的提示中说“stupid”呢……

**Comment by 1773798978** [comment]
![1586763583(1)](https://user-images.githubusercontent.com/61928538/79102298-0aa2cb80-7d9d-11ea-9eed-2702973685de.png)
这是在except后的括号加入KeyError的结果
![1586763724(1)](https://user-images.githubusercontent.com/61928538/79102515-7a18bb00-7d9d-11ea-902a-2f87731fdd15.png)
![1586763737(1)](https://user-images.githubusercontent.com/61928538/79102526-7c7b1500-7d9d-11ea-9ba0-5e1697f7ef4b.png)
我在网上看到了一个，在用户输入那一行代码中加.get的方法。
但我并不清楚这个方法的原理，并且出现了新的错误
我又在except后的括号加入AttributeError
[Uploading 1586764220(1).png…]()
结果是不会出现错误了但是，我的程序完全失效了....
它无法做出计算，也无法用那四个指令退出了
我觉得应该是get并不适用我这个情况，，但我并不清楚原因

我原本是想用这个异常处理解决一切用户胡乱输入的问题。可能方法不对

关于这个加入stupid。不知道老师有没有玩过史丹利的寓言，我想把它当成一个类似的游戏来设计。只是一个比较个人的东西，并不是个产品，所以我觉得应该没关系吧

**Comment by neolee** [comment]
我稍微研究了一下，这里可能和 `simpleeval` 包处理 `KeyError` 的方式有关系，所以只是捕获 `KeyError` 还是会出问题。

`KeyError` 是一个和数据容器 `dict`（字典）有关的运行时异常，简单说就是在这个容器里找不到指定名字的数据，你在网上搜到的 `get()` 方法也是和 `dict` 的处理有关的一种解决方案，这部分在后面我们学数据容器的时候会讲到，这个解决方案不能解决你的问题。

我建议的坚决方案是这样的：不要只捕获 `KeyError`，而是所有异常都捕获；但不要在 `run()` 方法里，而应该在 `_think()` 方法里，只针对 `simple_eval(s)` 这行代码进行，我修改后的 `_think()` 方法大致如下：

```python
def _think(self, s):
    try:
        result = "Done. Result = " + simple_eval(s)
    except:
        result = "Sorry I can't understand"

    return result
```

而 `run()` 方法不需要使用 `try...except` 结构。

**Comment by 1773798978** [comment]
好的，谢谢老师
