### ISSUE TITLE
在 ConEmu 中输入 jupyter lab 后直接闪退

### ISSUE THREAD

**Issue by zwg0113** [neolee/wop-ecnu-pub#56]
![image](https://user-images.githubusercontent.com/61927136/79096581-28b5ff00-7d90-11ea-9f39-efee5ccede7a.png)

**Comment by neolee** [comment]
看你的截图，这没“闪退”啊，正在执行，如果很长时间没有显示什么信息的话，可能有问题。

一个常见的可能是防病毒工具可能干扰 Jupyter 的运行。

**Comment by zwg0113** [comment]
> 看你的截图，这没“闪退”啊，正在执行，如果很长时间没有显示什么信息的话，可能有问题。
> 一个常见的可能是防病毒工具可能干扰 Jupyter 的运行。

这是我输入的内容，按完回车后就闪退了，我关闭防病毒软件试试看

**Comment by zwg0113** [comment]
> 看你的截图，这没“闪退”啊，正在执行，如果很长时间没有显示什么信息的话，可能有问题。
> 一个常见的可能是防病毒工具可能干扰 Jupyter 的运行。

谢谢老师，已经解决了，是防病毒软件的原因
