### ISSUE TITLE
系统内多个 python 

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#58]
我在另一门选修课中老师要求安装 python 3.6.6 的版本，为了用 TensorFlow 深度学习。
可是我在下完 3.6.6 的这个版本后，在 ConEmu 中启用的 python 也变成了 3.6.6 的版本。
怎么解决这个问题呢？

**Comment by neolee** [comment]
没关系，3.6.6 也完全 OK。

**Comment by unicorn-xia** [comment]
好滴，谢谢老师！
