### ISSUE TITLE
ModultNotFoundError

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#59]
已经安装好了 fastnumbers，可还是提示错误。
<img width="393" alt="捕获" src="https://user-images.githubusercontent.com/61767345/79937247-f42afd00-848b-11ea-916e-058e8256eecd.PNG">

**Comment by neolee** [comment]
看上去安装包和你运行 Jupyter 的不是同一个 Python 环境。

而且你的 Python 也不是按照我的指南安装的吧？

**Comment by unicorn-xia** [comment]
是按照指南装的，但是后来我根据其他课程需要又安装了一个python。
大概我的电脑里有两套python，那我应该怎么办呢？

**Comment by neolee** [comment]
初学者，除非你确切知道自己在做什么，否则我是非常不推荐装多个 Python 的，目前你最好能卸掉一个，保留一个可用的 Python 环境，就不会出现你问的情况了。

**Comment by unicorn-xia** [comment]
好的，谢谢老师

**Comment by unicorn-xia** [comment]
老师，我下载了那个python，保留了按您的学习指南的python。
```powershell
Fatal error in launcher: Unable to create process using '"d:\python\python.exe"  "D:\python\Scripts\pip.exe" install fastnumbers': ???????????
```

**Comment by unicorn-xia** [comment]
问题解决了，刚刚那个 python 没有彻底卸载。
