### ISSUE TITLE
Jupyter Lab 打开出现问题

### ISSUE THREAD

**Issue by ECNUACRush** [neolee/wop-ecnu-pub#6]
老师您好，我输入 `jupyter lab`发现打不开书了：
![image](https://user-images.githubusercontent.com/49430264/75952337-6e59ef00-5ee9-11ea-8afb-7aa0abd37e3b.png)
但是用 `jupyter notebook` 可以打开：
![image](https://user-images.githubusercontent.com/49430264/75952405-9ea18d80-5ee9-11ea-8de8-5a6b4ac6ec3b.png)
请问一下是什么情况？

**Comment by neolee** [comment]
因为 Jupyter Lab 不支持老的 IE，你用其他比较新一点的浏览器，比如 Chrome，就可以了。

可以通过修改 Windows 缺省浏览器一劳永逸解决，也可以自己打开 Chrome 之类的浏览器，把你运行 `jupyter lab` 的命令行窗口里 `http://localhost...` 那一整行地址拷贝过去也可以。

**Comment by ECNUACRush** [comment]
谢谢！解决了。
