### ISSUE TITLE
关于全局变量

### ISSUE THREAD

**Issue by Joestarc** [neolee/wop-ecnu-pub#60]
<img width="1126" alt="屏幕快照 2020-04-26 下午9 19 47" src="https://user-images.githubusercontent.com/61925101/80308995-a05e4200-8804-11ea-96c4-5c9ce2e77689.png">
<img width="912" alt="屏幕快照 2020-04-26 下午9 21 43" src="https://user-images.githubusercontent.com/61925101/80309006-a6ecb980-8804-11ea-8359-51fd251748db.png">
已经声明了全局变量了，为什么还是会报错？

**Comment by Joestarc** [comment]
<img width="1126" alt="屏幕快照 2020-04-26 下午9 19 47" src="https://user-images.githubusercontent.com/61925101/80309104-4f9b1900-8805-11ea-817d-45cc38e25ad6.png">
<img width="912" alt="屏幕快照 2020-04-26 下午9 21 43" src="https://user-images.githubusercontent.com/61925101/80309105-51fd7300-8805-11ea-91f6-51d0e2c7df2e.png">

**Comment by neolee** [comment]
如果你要使用全局变量，那么在所有用到的函数里都要用 global 关键字来说明。

不过还是课上强调的，我非常反对使用全局变量，在绝大多数情况下，都不需要使用全局变量，你这几个 bot 要共享一些数据的话，有很多更好的办法。
