### ISSUE TITLE
Windows 下 datetime 出错

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#62]
果然，我踩坑了。

1. `t.tzinfo`乱码
<img width="228" alt="1" src="https://user-images.githubusercontent.com/61767345/80466723-83924d80-896f-11ea-9b83-bbe0d29450af.PNG">

2. 有中文时出现`UnicodeEncodeError`
<img width="563" alt="2" src="https://user-images.githubusercontent.com/61767345/80466819-9d339500-896f-11ea-9a9e-5c1107cb6361.PNG">

3. 只做部分转化时出错
<img width="300" alt="3" src="https://user-images.githubusercontent.com/61767345/80467092-f4396a00-896f-11ea-923f-68e06f7e0216.PNG">
<img width="315" alt="4" src="https://user-images.githubusercontent.com/61767345/80467136-04514980-8970-11ea-8a80-983e43c71cfa.PNG">

谢谢老师！

**Comment by jingluo-star** [comment]
有同样的问题，连乱码都是一样的   ε=(´ο｀*)))

**Comment by neolee** [comment]
你碰的坑很全面（噗）所以就回你吧。

**[1] 格式化字符串（*format string*）中包含中文时报 UnicodeEncodeError**

这个和你的系统本地区域设置有关，这是个十分复杂的问题，尤其是在 Windows 这样历史包袱极重的系统中，它同时支持太多不同的体系，导致很大的混乱，目前没必要太深入，我们找到一些解决方案就可以了。

你可以在 Python 解释器或者 Jupyter Notebook 中运行下面的代码来查看你当前的设置：
```python
import locale
locale.getlocale()
```
很大可能返回是 `(None, None)`，解决方案是用下面的代码来设置本地语言环境：
```python
locale.setlocale(locale.LC_CTYPE, 'chinese')
```
另一种解决方案是不去动 `locale` 这样的神坑，转而避免使用带中文的格式化串，先把 `datetime` 对象转换成没有中文的字符串，再把其中特定字符换成我们想要的中文字符，大致这样（注意这个 `.format` 是字符串类型的方法，这个方法实际上就是我们讲过的 f-string 的底层实现）：
```python
t.strftime('%Y{y}%m{m}%d{d}').format(y='年', m='月', d='日')
```

**[2] `tzinfo` 显示乱码**

如果你的 Windows 系统语言选择是“中文”，而你 Python 中的 locale 设置不是 `chinese` 就有可能出现这个问题，用上一个问题中的 locale.setlocale(locale.LC_CTYPE, 'chinese') 通常也可以解决这个问题。

或者学我，系统语言选择“English”，那么这里会显示英文的 “Chinese Standard Time”。对写程序的人来说，使用英文系统会少不少麻烦——副作用是，你发现不了你的程序对中文环境的兼容性问题。

**[3] `strptime` 中使用的格式化字符串必须完整匹配字符串里所有内容**

`strptime` 中使用的格式化字符串必须**完整匹配**字符串里所有内容，否则 parsing 会失败，所以你的字符串里包含日期、星期和时间，而 parsing 的时候的格式化字符串却只有前半截，这会导致 `ValueError`。

另外这里也会遇到本地化问题，比如，假设你的字符串里星期是用中文的，在英文环境下 parsing 也会出问题，反之亦然。

**Comment by neolee** [comment]
@jingluo-star 当然一样啊，因为所谓“乱码”并不是随机混乱的字符，而是特定语言的字符被错误的当做别的语言，而出现的显示错误。你看到的乱码其实是“中国标准时间”被错误的当做 ASCII 字符而显示出来的结果。

顺便，关于字符集和编码，有兴趣可以看看[这篇文章](http://www.ligang.name/?p=241)，了解一些历史。

**Comment by unicorn-xia** [comment]
所有问题都完美解决啦，谢谢老师！
