### ISSUE TITLE
python 运行时内存的占用

### ISSUE THREAD

**Issue by siriuszza** [neolee/wop-ecnu-pub#64]
![image](https://user-images.githubusercontent.com/61924224/81574588-93cb1380-93d8-11ea-8957-9d9f8bc86ba9.png)
运行完这个代码，py大概占了1个多G（线性素数筛）
想知道py 各种不同的数据类型储存在内存里和字节是怎么换算的，字典，列表，元组每个元素占用的内存是否一样

**Comment by neolee** [comment]
Python 里一个 int 是 4 字节（32 位整数），你这端代码计算了一亿以下的整数，程序中包含双重循环，具体计算有点小复杂，我们可以简化一点，模糊的算一个整数用了两个 int 来计算，就是 8 字节，那么就差不多将近 1G 字节了。
