### ISSUE TITLE
关于寻找素数的2个问题

### ISSUE THREAD

**Issue by LauraWen** [neolee/wop-ecnu-pub#65]
1.在不做任何改动的情况下运行同一段代码，为什么会时间不一样呢？
![image](https://user-images.githubusercontent.com/46390542/82137174-491e2100-9848-11ea-9641-66e16193a1d4.png)
2.按照您给的筛法实现寻找素数的iterator版本，提示报错。我反复比对过您在幻灯片上展示的代码都是一样的，有点疑惑不知道哪里出问题了。🤦‍
![image](https://user-images.githubusercontent.com/46390542/82137320-89ca6a00-9849-11ea-9a4e-453f9a1d2ef9.png)

**Comment by LauraWen** [comment]
![image](https://user-images.githubusercontent.com/46390542/82137990-630f3200-984f-11ea-8242-46a7a55780ad.png)

**Comment by neolee** [comment]
1. 这个误差属于正常，比如说你第一次运行时正好操作系统后台运行了一个什么任务，分了你一些计算资源，所以我们做 performance test 一般都是运行许多次然后取平均值。

2. 你没实现 `__iter__()` 方法，幻灯片里为了省地方没写这个方法，但所有 iterable object 都需要这个方法，否则无法被 `for...in` 循环处理，你可以看看我写的 `for...in` 循环的原理实现，里面是要用到 `__iter__()` 方法的。

**Comment by LauraWen** [comment]
好的，谢谢老师。看来还是iterator没吃透。
