### ISSUE TITLE
云服务器/Linux

### ISSUE THREAD

**Issue by WendelKu** [neolee/wop-ecnu-pub#66]
1.Mac下有没有什么比较好的ssh工具，能够像xshell方便地建立与云服务器的连接并发送命令？
2.在ubuntu下用命令行下载第三方程序包往往会因为断网(我的电脑是这样)而安装失败，而再次输入同样的命令下载同样的第三方程序包时，程序包存储的路径与上次的下载到一半而失败的往往不同；而下载到一半而失败因为没有删除而占用了很多空间。这很容易导致ubuntu崩溃(因为我用的是vmware下的虚拟机)。这逼迫我时不时的得存储磁盘映像而返回，浪费了大量时间。有没有什么办法能快速删去这些坏失(下载失败)的程序包，而不用知道这些程序包所在的位置？

**Comment by neolee** [comment]
1. 首先 xshell 不是 ssh，只是一个 shell 管理器，类 Unix 的系统都不需要这种东西，因为所有类 Unix 系统都自带 shell 全套工具，macOS 下自带的 Terminal.app 就很好用，进入 Terminal 就可以使用 ssh 命令访问远程服务器了。

2. 这问题说的不太清楚，有很多信息没提供，比如：
- 你用什么下载第三方程序？如果 Ubuntu，一般都会用 Debian 的缺省包管理系统 apt，这个系统支持断点续传，网络中断了再试的时候会接着之前的下载继续，不会产生垃圾文件，apt 也提供了完备的 archive 清理功能；
- 即使硬盘空间不足也不会那么容易崩溃，即使用虚拟机也不会，Linux 可没那么脆弱，你碰到崩溃的具体原因确定是这个吗？
- 虚拟机提供的快照保存和恢复是个辅助功能，很少会用到，经常用这个肯定是有问题；
- 你为什么想“快速删去一些东西而不用知道它们在哪里”？这是个不对的思维，至少不适合使用 Linux 操作系统，Linux 是给服务器和工程师的计算机用的，你要安装点什么或者删除点什么最好知道它在哪儿；如果你只想把计算机当做微波炉一样的黑盒子使用，那就用 Windows，而且只用官方的图形化界面工具，出了问题找客服，就行了。

最后，这些问题似乎与我们的课程没啥关系吧，我们的课程是编程的入门课， 我建议在入门编程的时候使用自己最熟悉的系统环境，严格按照我们提供的环境配置指南操作，这样可以把学习主题以外的干扰降到最低。如果要学习 Linux，那是另一门课了，从你的问题推测你对类 Unix 操作系统并不熟悉，那要学习的基础还不少。
