### ISSUE TITLE
关于示例代码的一点疑问

### ISSUE THREAD

**Issue by ccccchao** [neolee/wop-ecnu-pub#67]
![image](https://user-images.githubusercontent.com/47491257/82971260-df9ad100-a004-11ea-9f6b-c28349331474.png)
老师好，在已经写了如图第11行的代码的情况下，第20行add_child中的node.parent=self是不是没有必要写？

**Comment by neolee** [comment]
`add_child` 是一个泛用的方法，不止用在 `__init__` 中，所以第20行是必须的，有了这一行 `add_child` 才是一个完整独立的概念实现，符合我们写函数要“高内聚、低耦合”的原则。

在上述结论基础上，倒是 `__init__` 中的相关片段可以做一些优化，你可以尝试下。

**Comment by ccccchao** [comment]
明白了，谢谢老师
