### ISSUE TITLE
关于大作业中 find 函数的一点疑问

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#68]
老师，find 函数要返回什么东西呢？比如
```python
find('河北省')
```
1. 如果只是要返回是否能找到，会不会过于简单了一些？
2. 如果返回的是 node 节点的话，是否没有实际意义？
3. 我本来想的是返回 `河北省` 的位置信息，可是 `get_tier()` 已经实现返回他的层级
4. 还是说返回的内容是根据自己需求所定呢？

**Comment by neolee** [comment]
返回找到的 node 对象就好。你可以想一想为什么这是相对最好的方式。

**Comment by unicorn-xia** [comment]
好的，谢谢老师！
