### ISSUE TITLE
关于 remove 方法的疑惑

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#69]
不确定这个问题可不可以问~
但我关于 `remove(self, node)` 方法有点疑惑，我想的是现有两种可能的实现方式。
1. `remove` 方法实现过程中与 `self` 无关
     * 优势是可以实现跨层级操作，如 `root.remove(c21)`
     * 劣势是可以容忍某些错误，如 `b.remove(c21)` 也可以执行
2. `remove` 方法实现过程中与 `self` 有关
     * 优势是操作很清晰
     * 劣势是此时实现方法必须是 `父节点.remove(子节点)`，否则会出错

然后，我就很纠结很纠结，我觉得两种方式都挺好的，不知道该用哪一种。

**Comment by neolee** [comment]
`node1.remove(node2)` 方法的含义是：从“以 node1 为根节点的树”中移除节点 node2。

这隐含的前提条件是：node2 是“以 node1 为根节点的树”中的一个节点，如果不是这样，并没有什么意义。

其它的就需要你自行分析了。
