### ISSUE TITLE
安装 jupyterlab/toc 错误

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#7]
![7d8af729a2ac80fb2504083a6fe0198](https://user-images.githubusercontent.com/61767345/75977173-cb1fce80-5f16-11ea-85df-d89c9c152d13.jpg)
上网搜了一下，仍没有找到答案，请问老师是什么原因呢？
谢谢老师！

**Comment by sunshinemingo** [comment]
你可以检查一下自己的JupyterLab的版本，参考一下https://github.com/jupyterlab/jupyterlab-toc/issues/27，也许可以帮到你

**Comment by neolee** [comment]
试试先安装下 nodejs，Jupyter Lab 编译有些插件需要它：

```shell
scoop install nodejs
```

**Comment by unicorn-xia** [comment]
已安装nodejs
执行` jupyter lab --version ` ，结果是2.0.0 ，应为最新版本。
上网查找，尝试执行` jupyter labextension install @jupyterlab/toc@2.0.0 `
结果是```
An error occured.
ValueError:"@jupyterlab/toc@2.0.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/application
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/apputils
>=4.0.0 <4.1.0          >=3.0.0 <4.0.0 @jupyterlab/coreutils
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/docmanager
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/fileeditor
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/notebook
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/rendermime
See the log file for details:  C:\Users\dell\AppData\Local\Temp\jupyterlab-debug-a_9g9_vt.log
```
看到以前的issues有说jupyterlab/toc已经release 2.0.0版本，但我尝试仍然失败。
我想问的是：
* 以上代码是什么意思？
* 不知应该如何解决这个问题？
谢谢！

**Comment by neolee** [comment]
Jupyter Lab 太新啦，插件还没来得及更新，先不装吧。

**Comment by neolee** [comment]
目前 toc 插件已经更新支持最新的 JupyterLab 了，有需要的同学可以尝试安装/更新。

**Comment by unicorn-xia** [comment]
刚刚又尝试了以下。执行
 ```powershell
 jupyter labextension install @jupyterlab/toc@2.0.0 
```
依然提示不兼容
```powershell
An error occured.
ValueError:"@jupyterlab/toc@2.0.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/application
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/apputils
>=4.0.0 <4.1.0          >=3.0.0 <4.0.0 @jupyterlab/coreutils
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/docmanager
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/fileeditor
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/notebook
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/rendermime
See the log file for details:  C:\Users\dell\AppData\Local\Temp\jupyterlab-debug-a_9g9_vt.log
```
但是又出现了一个新的问题:
执行
```powershell
jupyter labextension install @jupyterlab/toc 
```
提示
```powershell
 Building jupyterlab assets (build:prod:minimize) 
```
我上查了一下，没有找到有用的回答。
这个插件是否有别的安装方法呢？（类似 VS Code 可以打开软件安装插件）
麻烦老师！

**Comment by neolee** [comment]
你执行 `jupyter labextension install @jupyterlab/toc` 就可以了，不要指定具体版本。

**Comment by unicorn-xia** [comment]
安装成功啦！
谢谢老师！
