### ISSUE TITLE
列表作为缺省值参数时的坑

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#70]
我在复习递归算法时随便写了一点东西，但出现了一个诡异的情况：

我定义了一个列表作为缺省值参数的函数，如下
```python
def f(n, l=[]):
    if n == 0:
        return
    else:
        l.append(n)
        f(n-1, l)
        
    return l
```
然后两次 `print(f(5))`，发现结果不一样。

第一次结果是 `[5, 4, 3, 2, 1]`，第二次结果是 `[5, 4, 3, 2, 1, 5, 4, 3, 2, 1]`

看起来好像是两次调用操作的是同一个列表，但第二次调用函数时，在默认缺省值 `l = []` 时，没有重置列表数据吗？

**Comment by neolee** [comment]
这个问题和“列表类型的带缺省值参数”没有直接关系，关键是你改变了输入参数的内容然后又把它返回了，这个操作建立了返回值（本质上在 global scope）和函数参数值（本质上在 local scope）之间的链接，指向同一个列表对象，从而造成这个对象存在持续化。你可以看看我以前的一个回答：

https://github.com/neolee/pilot/issues/1310

总的来说，应避免这种“改变了输入参数的内容然后直接将它返回”的设计，如果你把代码改成类似下面这样就不会有问题了：

```python
def f(l=[]):
    return l + [7]

print(f())
print(f())
```

想想这和你原先的版本有什么区别？

**Comment by unicorn-xia** [comment]
哦哦，老师这种方法并没有直接改变 `l` 本身！谢谢老师！
