### ISSUE TITLE
重装系统后配置环境出现问题

### ISSUE THREAD

**Issue by jkx112** [neolee/wop-ecnu-pub#71]
老师好，我前两天重装系统，删掉了应用程序，但是保留文件。重新配置出现这样的问题 
![1](https://user-images.githubusercontent.com/61953867/83260069-b7b99200-a1eb-11ea-98ae-35c9ce2ed77e.png)显示已经安装scoop但是更新就说无法找到scoop
![2](https://user-images.githubusercontent.com/61953867/83260141-d61f8d80-a1eb-11ea-9d5a-3ebe6a755583.png)
我之前下载的python程序还在，但是用这个也没办法安装jupyterlab
![QQ图片20200529203103](https://user-images.githubusercontent.com/61953867/83260289-1a129280-a1ec-11ea-8a3e-0ed981259f6f.png)
能用vscode写python代码。
这个要怎么处理

**Comment by neolee** [comment]
感觉是 Scoop 需要的 PATH 没设置好，重装一次 Scoop 比较保险，点这个页面上面的 Wiki 里面有方法。
