### ISSUE TITLE
添加if __name__ == '__main__'之后运行错误

### ISSUE THREAD

**Issue by decodejerome** [neolee/wop-ecnu-pub#74]
老师好，我在加了if __name__ == '__main__'这个之后，出现了错误。不知道原因是什么。请帮忙看下。

<img width="730" alt="微信截图_20200601215948" src="https://user-images.githubusercontent.com/59760263/83416529-64e21380-a453-11ea-9ec8-385a4d877e50.png">
<img width="719" alt="微信截图_20200601215905" src="https://user-images.githubusercontent.com/59760263/83416541-690e3100-a453-11ea-9edf-1c1df244e17f.png">

**Comment by neolee** [comment]
这一行最后少了个 `:` 啊，还记得 `if` 的语法么？

**Comment by Jerome818** [comment]
> 这一行最后少了个 : 啊，还记得 if 的语法么？

啊！谢谢。哎……哭了……想半天。然后改了之后要stage all changes 才能运行。
