### ISSUE TITLE
数据分析师相关问题咨询

### ISSUE THREAD

**Issue by unicorn-xia** [neolee/wop-ecnu-pub#76]
听了您的漫游指南后，对数据分析师十分感兴趣，也有很多疑问，最近期末论文写完之后，就跑来问您问题了~
我是统计专业，早早就听过数据分析师这个岗位，一直都没有深入了解过。然后最近在网上看了很多篇文章，每个人说的都不一样。有人说数据分析师人才极度稀缺，有人说大部分公司招的所谓的数据分析师其实就是做做Excel......
所以我想问：
1. 数据分析师的日常到底是什么样子的呀？
2. 统计学专业出身应该是有数理基础和一定的 python 编程能力，想要学习 SQL 知识，应该怎么样入手或者是有没有好的学习资源推荐呢？其实更希望老师后续会开这样的课程啦！

谢谢老师~

**Comment by neolee** [comment]
1. 这个问题，不同的公司可能会有差别，一般来说数据分析师的工作是从业务部门拿到一个业务问题，然后建立这个业务问题和具体数据之间的关联，然后转化为数据需求，有时候会提给数据部门的技术人员，有时候就自己去取数了，总之最后是拿数据来回答业务部门的那个问题。

2. 说实话这个岗位挺难坐在家里学会的，最好的办法是找个靠谱点的团队去实习，一边学业务，一边学数据库里的数据。
