### ISSUE TITLE
FSM 中的函数执行之后 state 为什么没有变化?

### ISSUE THREAD

**Issue by yeghub** [neolee/wop-ecnu-pub#78]
from transitions import Machine
class st(object):
    def melt(self):
        print('it is melting!')
    def evaporate(self):
        print('it is evaporating')
lump = st()
states= ['solid','liquid','gas','plasma']
transitions = [
    {'trigger':'melt','source':'solid','dest':'liquid'}  ,
    {'trigger':'evaporate','source':'liquid','dest':'gas'}  
]
machine = Machine(lump,states= states,transitions= transitions,auto_transitions = True,initial= 'soild')

lump.state
lump.melt()
print(lump.state)
lump.evaporate()
print(lump.state)

运行结果如下：
it is melting!
soild
it is evaporating
soild

melt()执行之后，state应该是liquid,为什么还是soild?
evaporate()执行之后，state应该是gas,为什么还是soild?

**Comment by neolee** [comment]
首先，你应该先学习下如何贴代码，你这代码根本没法看嘛……

然后，你可能误解了 `transitions` 这个第三方库里 `trigger` 的概念。在这个库里，`trigger` 是在 `transition` 里定义的一个名字，这个名字会自动被注册到 model 中（在你的例子里就是 `st` 类型的对象 `lump`），成为一个可以使用的方法，这个方法是不需要（也不能自己定义的）。

所以当你在 `st` 中定义了名为 `melt` 和 `evaporate` 的方法时，实际上覆盖掉了 `transitions` 帮你加进去的那两个 trigger 方法，你的 `lump.melt()` 调用的是你定义的方法而不是 trigger，所以没有产生状态转移的效果。

如果你需要在状态转移时额外执行你写的代码，需要用 transition 里的 `before` 和 `after` 参数来指定，教材里有例子。

**Comment by yeghub** [comment]
```
from transitions import Machine
class st(object):
    pass

lump = st()
states= ['solid','liquid','gas','plasma']
transitions = [
    {'trigger':'melt','source':'solid','dest':'liquid'}  ,
    {'trigger':'evaporate','source':'liquid','dest':'gas'}  
]
machine = Machine(lump,states= states,transitions= transitions,auto_transitions = True,initial= 'soild')

print(lump.state)
lump.melt()
print(lump.state)
lump.evaporate()
print(lump.state)
```
感谢李老师，根据老师的意见
1、重新粘贴了代码
2、对trigger有了新的认识，修改代码，实现预期效果
