### ISSUE TITLE
Scoop下载出错

### ISSUE THREAD

**Issue by LLLLLiang** [neolee/wop-ecnu-pub#79]
![scoop无法正常安装](https://user-images.githubusercontent.com/71803224/94094606-80ce5280-fe52-11ea-82c0-5da2bb564c25.PNG)
试着在网上查询了，但是那个方法我不会弄，请问怎么解决？

**Comment by gymgym1212** [comment]
@LLLLLiang 可以先参考老师这篇解答  https://github.com/neolee/wop-ecnu-pub/wiki#附访问-github-的一些问题 

这可能和你在网上搜索到的方案是类似的，但是老师总结的步骤很精炼，请注意一字一字精读，以避免一些步骤被忽略而导致的错误。
