### ISSUE TITLE
ConEmu 中输入 code 显示为不可执行命令

### ISSUE THREAD

**Issue by ECNU2036** [neolee/wop-ecnu-pub#8]
但在Windows自带命令行中输入” code.cmd " 可以打开VSCode
![截图1](https://user-images.githubusercontent.com/61863257/76060499-68810e00-5fbc-11ea-93c3-fdfe47b06833.png)

**Comment by neolee** [comment]
如果你下载并安装了 Visual Studio Code 的最新稳定（Stable）版本，并至少打开运行过一次的话，它会自动安装好 `code` 这个命令行命令。

如果在确认上述条件之后，仍然出现截图中的问题，可以尝试重启一下 Windows，有的系统需要重启才能让配置生效。

另外，你可以执行一下下面的命令，给我看看结果：

```powershell
$env:Path
```

**Comment by ECNU2036** [comment]
重启之后就可以运行了，谢谢！
![截屏2](https://user-images.githubusercontent.com/61863257/76064772-4c359f00-5fc5-11ea-82d0-7f29e769d035.png)

**Comment by neolee** [comment]
Nice!
