### ISSUE TITLE
scoop 自动检索命令报错

### ISSUE THREAD

**Issue by fengzhihuixue** [neolee/wop-ecnu-pub#80]
![(NM_Y0HAMPD(HE8AI$V}R9](https://user-images.githubusercontent.com/71932925/94342390-5abbd480-0043-11eb-9ef4-25c107dd3648.png)
这该咋办啊。。。。

**Comment by neolee** [comment]
从出错信息看 Scoop 没装好，命令行找不到 scoop 这个命令。

**Comment by fengzhihuixue** [comment]
![image](https://user-images.githubusercontent.com/71932925/94358384-23950400-00d3-11eb-97e7-647dd8085d06.png)
可是现在这个安装命令也报错

**Comment by gymgym1212** [comment]
@fengzhihuixue 可以参考上个issue #79

**Comment by neolee** [comment]
如 @gymgym1212 所说，这是访问 GitHub 的域名出错，Wiki 里有解决方案。
