### ISSUE TITLE
Scoop 执行安装命令报错

### ISSUE THREAD

**Issue by hive28** [neolee/wop-ecnu-pub#81]
<img width="483" alt="issue" src="https://user-images.githubusercontent.com/71964384/94360772-93f75180-00e2-11eb-8c8d-9c35c1eda36e.png">
如图

**Comment by neolee** [comment]
访问 GitHub 的域名出问题，请参考 #79 ，Wiki 里有解决方案。

**Comment by wuhao0120** [comment]
我也是遇到这种情况  我连上学校的VPN再进行安装就没问题了

**Comment by hive28** [comment]
已解决，谢谢
