### ISSUE TITLE
Git 安装报错

### ISSUE THREAD

**Issue by Albert-Li0617** [neolee/wop-ecnu-pub#86]
![图片](https://user-images.githubusercontent.com/72544378/95477674-2f2dd800-09bb-11eb-8b10-7235d9755eba.png)

**Comment by neolee** [comment]
这个问题一般是下载的 Git 安装包不完整导致的。可以参考下面这个问题里的方法：

https://github.com/neolee/wop-community/issues/11

**Comment by Albert-Li0617** [comment]
感谢老师的回复。
   下载安装包 https://github.com/git-for-windows/git/releases/download/v2.27.0.windows.1/PortableGit-2.27.0-64-bit.7z.exe#/dl.7z 下载回来的安装包名称是 ProtableGit-2.27.0-64-bit.7z.exe；
    复制这个安装包到 scoop 的 cache 目录后改文件名为 git#2.27.0.windows.1#https_github.com_git-for-windows_git_releases_download_v2.27.0.windows.1_PortableGit-2.27.0-64-bit.7z.exe_dl.7z；
   使用这个方法操作了，还是不行。
第一个git是自己下载的文件，第二个git是执行scoop install git自己生成的。
![图片](https://user-images.githubusercontent.com/72544378/95562397-b1b3a780-0a4e-11eb-8c9f-88e2199f0c41.png)
![图片](https://user-images.githubusercontent.com/72544378/95562417-b7a98880-0a4e-11eb-8f40-21d558278842.png)

**Comment by Albert-Li0617** [comment]
去Git官网安装完了，是否也可以？
可以执行scoop update指令了，但是没有出现在scoop list中，是否会影响后续使用？

**Comment by neolee** [comment]
让你参考的帖子是一段时间以前的，当时 git 是 2.27 版本，现在已经是 2.28 版本了（看你最开始下载的截屏就能看到），所以自然下载和改名的时候也要做相应的变化，否则就不对了。

直接 Git 官网下载安装也可以，后续操作能顺利进行就行。
