### ISSUE TITLE
jupyter lab 无法启动服务端

### ISSUE THREAD

**Issue by jasonli-qznx** [neolee/wop-ecnu-pub#9]
![jupyter lab无法启动服务端](https://user-images.githubusercontent.com/61810039/76082942-697b6500-5fe7-11ea-869e-b03086dd3351.PNG)
运行jupyter lab 就卡死，无法启动服务后台

**Comment by neolee** [comment]
你有没有在使用什么防火墙或者防病毒工具？如果有的话，先停用再试试？

**Comment by jasonli-qznx** [comment]
已解决，是系统的防火墙的原因。谢谢李老师。
