### ISSUE TITLE
没有保存文件权限

### ISSUE THREAD

**Issue by 10203901427** [neolee/wop-ecnu-pub#90]
老师，请问这样操作以后是直接关闭窗口还是怎么弄？
![image](https://user-images.githubusercontent.com/71881365/96336529-0b514d00-10b3-11eb-8e53-2d11be44990f.png)
我重启过后还是没有权限
![image](https://user-images.githubusercontent.com/71881365/96336573-6daa4d80-10b3-11eb-9a23-9e9a182fbe92.png)

![image](https://user-images.githubusercontent.com/71881365/96336584-7a2ea600-10b3-11eb-96ae-f3683c69e8e6.png)

![image](https://user-images.githubusercontent.com/71881365/96336589-8155b400-10b3-11eb-8372-4eed09c671da.png)
![image](https://user-images.githubusercontent.com/71881365/96336596-8b77b280-10b3-11eb-8e1d-0550a44ba4b9.png)
请老师帮忙看看是哪里错了

**Comment by neolee** [comment]
建议你用 Visual Studio Code 打开和编辑 hosts 文件，然后保存时 VS Code 会提示权限不足，是否启用管理员权限，选 Yes 即可。
