### ISSUE TITLE
关于VSCode

### ISSUE THREAD

**Issue by LLLLLiang** [neolee/wop-ecnu-pub#92]
请问怎么在VSCode 中新建一个python文件？直接新建文件只有一个untitled 1。

**Comment by gymgym1212** [comment]
保存新建的文件名为 xxx.py即可。

也推荐按照李老师的学习指引进行设置。当然，探索精神也是计算机学习中很重要的部分:)

**Comment by neolee** [comment]
上次说的 https://github.com/neolee/wop-ecnu-pub/wiki/Video-Lectures 这里的支线课程，都看了学了吗？
