### ISSUE TITLE
notebook 突然无法使用

### ISSUE THREAD

**Issue by LLLLLiang** [neolee/wop-ecnu-pub#95]
在学习用书目录中打开jupyter lab，notebook无法在输入代码处使用shift 和 backspace

**Comment by LLLLLiang** [comment]
就突然无法使用了，在这里提问也还能正常使用

**Comment by neolee** [comment]
有更多信息么？比如截图之类的（包括你运行 jupyter lab 的命令行界面和打开 Lab 的浏览器）？

**Comment by LLLLLiang** [comment]
![错误](https://user-images.githubusercontent.com/71803224/97108246-3701b200-1707-11eb-8e8f-a610f10f30f2.jpg)
请问这样可以吗？按照之前教程所说打开notebook，之前可以在上面打字，现在只能拖到最上面一个空格，然后按tab，切换到第二个空格处打字，而且无法使用backspace，很奇怪

**Comment by neolee** [comment]
从你的描述看是比较奇怪的状况，你可以找在学校的老师问问，或者等周三上课给我看看。
